<?php

/*
|--------------------------------------------------------------------------
| خريطةُ المزوّدين — **مولَّدةٌ لا تُحرَّر**
|--------------------------------------------------------------------------
|
| المصدر: قياسُ شيفرةِ LiteLLM v1.101.0 بـ
| `deploy/litellm/tools/measure_providers.py`، ثمّ تصنيفُ
| `AiProviderRegistry::classify()`. لتوليدِها من جديد:
|
|     php artisan hub:ai-provider-map
|
| **وتحريرُها بيدٍ يُمحى عند أوّلِ توليد.** التصحيحُ موضعُه قاعدةٌ في
| `AiProviderRegistry` أو مدخلٌ مكتوبٌ بيدٍ في `config/ai_catalog.php`.
|
| **ومزوّدٌ غائبٌ عن هذه الخريطةِ يعمل**: السجلُّ يسقط إلى الافتراضِ
| (`api_key`) فيُنتج مدخلاً صالحاً بلا تغييرِ شيفرة. فالخريطةُ تسريعٌ
| ودقّةٌ، لا شرطُ عمل.
|
*/

return [

    'source' => [
        'litellm_version' => '1.101.0',
        'generator'       => 'deploy/litellm/tools/measure_providers.py',
        'classifier'      => 'App\\Support\\Ai\\Catalog\\AiProviderRegistry::classify',
        'providers'       => 155,
    ],

    'snapshot' => [
        'a2a',
        'a2a_agent',
        'ai21',
        'ai21_chat',
        'aiml',
        'aiohttp_openai',
        'amazon_nova',
        'anthropic',
        'anthropic_text',
        'apertis',
        'assemblyai',
        'auto_router',
        'aws_polly',
        'azure',
        'azure_ai',
        'azure_text',
        'baseten',
        'bedrock',
        'bedrock_mantle',
        'black_forest_labs',
        'bytez',
        'cerebras',
        'charity_engine',
        'chatgpt',
        'chutes',
        'clarifai',
        'cloudflare',
        'codestral',
        'cognition',
        'cohere',
        'cohere_chat',
        'cometapi',
        'compactifai',
        'cursor',
        'custom',
        'custom_openai',
        'darkbloom',
        'dashscope',
        'databricks',
        'datarobot',
        'deepgram',
        'deepinfra',
        'deepseek',
        'docker_model_runner',
        'dotprompt',
        'elevenlabs',
        'empower',
        'fal_ai',
        'featherless_ai',
        'fireworks_ai',
        'friendliai',
        'galadriel',
        'gdc',
        'gemini',
        'gigachat',
        'github',
        'github_copilot',
        'gradient_ai',
        'groq',
        'helicone',
        'heroku',
        'hosted_vllm',
        'huggingface',
        'humanloop',
        'hyperbolic',
        'inception',
        'infinity',
        'jina_ai',
        'lambda_ai',
        'langflow',
        'langfuse',
        'langgraph',
        'lemonade',
        'libertai',
        'litellm_agent',
        'litellm_proxy',
        'llamafile',
        'lm_studio',
        'manus',
        'maritalk',
        'meta',
        'meta_llama',
        'milvus',
        'minimax',
        'mistral',
        'modelscope',
        'mongodb',
        'moonshot',
        'morph',
        'nano-gpt',
        'nebius',
        'neosantara',
        'nlp_cloud',
        'novita',
        'nscale',
        'nvidia_nim',
        'nvidia_riva',
        'oci',
        'ollama',
        'ollama_chat',
        'oobabooga',
        'openai',
        'openai_like',
        'openrouter',
        'ovhcloud',
        'parasail',
        'perplexity',
        'petals',
        'pg_vector',
        'pinstripes',
        'poe',
        'predibase',
        'publicai',
        'qwen_ai_platform',
        'qwencloud',
        'ragflow',
        'recraft',
        'reducto',
        'replicate',
        'runwayml',
        's3_vectors',
        'sagemaker',
        'sagemaker_chat',
        'sagemaker_nova',
        'sambanova',
        'sap',
        'scaleway',
        'scx-ai',
        'snowflake',
        'soniox',
        'stability',
        'synthetic',
        'tencent',
        'tensormesh',
        'text-completion-codestral',
        'text-completion-inception',
        'text-completion-openai',
        'together_ai',
        'topaz',
        'triton',
        'v0',
        'valkey',
        'vercel_ai_gateway',
        'vertex_ai',
        'vertex_ai_beta',
        'vllm',
        'volcengine',
        'voyage',
        'wandb',
        'watsonx',
        'watsonx_text',
        'xai',
        'xiaomi_mimo',
        'xinference',
        'zai',
    ],

    'providers' => [

        'a2a' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => false, 'require_api_base' => true],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'a2a_agent' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'no_chat_surface',
            'discovery' => 'manual',
            'modalities' => [],
        ],
        'ai21' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'ai21_chat' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => false, 'require_api_base' => true],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'aiml' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['image_generation'],
        ],
        'aiohttp_openai' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => false, 'require_api_base' => true],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'amazon_nova' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'anthropic' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['anthropic_messages', 'files', 'skills_api', 'text_completion'],
        ],
        'anthropic_text' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'apertis' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'assemblyai' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'auto_router' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'no_chat_surface',
            'discovery' => 'manual',
            'modalities' => [],
        ],
        'aws_polly' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:text_to_speech',
            'discovery' => 'manual',
            'modalities' => ['text_to_speech'],
        ],
        'azure' => [
            'auth' => 'api_key_endpoint_version',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED',
            'modalities' => ['audio_transcription', 'chat', 'container', 'image_edit', 'image_generation', 'passthrough', 'realtime_http', 'responses_api', 'text_to_speech', 'vector_stores', 'video'],
        ],
        'azure_ai' => [
            'auth' => 'api_key_endpoint_version',
            'discovery' => 'live',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED',
            'modalities' => ['anthropic_messages', 'image_edit', 'image_generation', 'ocr', 'rerank', 'text_completion', 'vector_stores'],
        ],
        'azure_text' => [
            'auth' => 'api_key_endpoint_version',
            'discovery' => 'live',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED',
            'modalities' => ['container'],
        ],
        'baseten' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'bedrock' => [
            'auth' => 'aws_signature',
            'discovery' => 'live',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED_WITH_SPECIAL_AUTH',
            'modalities' => ['anthropic_messages', 'batches', 'files', 'image_edit', 'passthrough', 'text_completion', 'vector_store', 'vector_stores'],
        ],
        'bedrock_mantle' => [
            'auth' => 'aws_signature',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED_WITH_SPECIAL_AUTH',
            'modalities' => ['passthrough', 'responses_api'],
        ],
        'black_forest_labs' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:image_edit,image_generation',
            'discovery' => 'manual',
            'modalities' => ['image_edit', 'image_generation'],
        ],
        'bytez' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'cerebras' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'charity_engine' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'chatgpt' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => false, 'require_api_base' => true],
            'status' => 'SUPPORTED',
            'modalities' => ['responses_api'],
        ],
        'chutes' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'clarifai' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['text_completion'],
        ],
        'cloudflare' => [
            'auth' => 'api_key_account',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'codestral' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'cognition' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'cohere' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['embedding', 'ocr', 'rerank'],
        ],
        'cohere_chat' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['embedding', 'rerank'],
        ],
        'cometapi' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['embedding', 'image_generation'],
        ],
        'compactifai' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'cursor' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'no_chat_surface',
            'discovery' => 'manual',
            'modalities' => [],
        ],
        'custom' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => false, 'require_api_base' => true],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'custom_openai' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'darkbloom' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'dashscope' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['embedding', 'image_generation', 'rerank'],
        ],
        'databricks' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['responses_api'],
        ],
        'datarobot' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'deepgram' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:audio_transcription',
            'discovery' => 'manual',
            'modalities' => ['audio_transcription'],
        ],
        'deepinfra' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['rerank'],
        ],
        'deepseek' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['anthropic_messages'],
        ],
        'docker_model_runner' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'dotprompt' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'no_chat_surface',
            'discovery' => 'manual',
            'modalities' => [],
        ],
        'elevenlabs' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:audio_transcription,text_to_speech',
            'discovery' => 'manual',
            'modalities' => ['audio_transcription', 'text_to_speech'],
        ],
        'empower' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'fal_ai' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:image_generation',
            'discovery' => 'manual',
            'modalities' => ['image_generation'],
        ],
        'featherless_ai' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'fireworks_ai' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['rerank', 'text_completion'],
        ],
        'friendliai' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'galadriel' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'gdc' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'gemini' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['audio_transcription', 'files', 'google_genai_generate_content', 'image_edit', 'image_generation', 'realtime', 'text_completion', 'vector_stores', 'video'],
        ],
        'gigachat' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['embedding', 'passthrough'],
        ],
        'github' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'github_copilot' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'interactive_oauth_on_gateway_host',
            'discovery' => 'catalog',
            'modalities' => ['anthropic_messages', 'embedding', 'responses_api'],
        ],
        'gradient_ai' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'groq' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'helicone' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'heroku' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'hosted_vllm' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => ['audio_transcription', 'embedding', 'passthrough', 'rerank', 'responses_api', 'text_completion', 'video'],
        ],
        'huggingface' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['rerank'],
        ],
        'humanloop' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'no_chat_surface',
            'discovery' => 'manual',
            'modalities' => [],
        ],
        'hyperbolic' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'inception' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'infinity' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:embedding,rerank',
            'discovery' => 'manual',
            'modalities' => ['embedding', 'rerank'],
        ],
        'jina_ai' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:embedding,rerank',
            'discovery' => 'manual',
            'modalities' => ['embedding', 'rerank'],
        ],
        'lambda_ai' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'langflow' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'langfuse' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'no_chat_surface',
            'discovery' => 'manual',
            'modalities' => [],
        ],
        'langgraph' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'lemonade' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['text_completion'],
        ],
        'libertai' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'litellm_agent' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'no_chat_surface',
            'discovery' => 'manual',
            'modalities' => [],
        ],
        'litellm_proxy' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['image_edit', 'image_generation', 'responses_api', 'text_completion'],
        ],
        'llamafile' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'lm_studio' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'manus' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:files,responses_api',
            'discovery' => 'manual',
            'modalities' => ['files', 'responses_api'],
        ],
        'maritalk' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'meta' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'meta_llama' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'milvus' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:vector_stores',
            'discovery' => 'manual',
            'modalities' => ['vector_stores'],
        ],
        'minimax' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['anthropic_messages', 'text_to_speech'],
        ],
        'mistral' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['audio_transcription', 'ocr'],
        ],
        'modelscope' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['image_generation'],
        ],
        'mongodb' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:vector_stores',
            'discovery' => 'manual',
            'modalities' => ['vector_stores'],
        ],
        'moonshot' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'morph' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'nano-gpt' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'nebius' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'neosantara' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'nlp_cloud' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'novita' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'nscale' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'nvidia_nim' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['rerank'],
        ],
        'nvidia_riva' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:audio_transcription',
            'discovery' => 'manual',
            'modalities' => ['audio_transcription'],
        ],
        'oci' => [
            'auth' => 'key_pair',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED_WITH_SPECIAL_AUTH',
            'modalities' => ['embedding'],
        ],
        'ollama' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['text_completion'],
        ],
        'ollama_chat' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['text_completion'],
        ],
        'oobabooga' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => false, 'require_api_base' => true],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'openai' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['audio_transcription', 'chat', 'container', 'evals_api', 'image_edit', 'image_generation', 'image_variation', 'realtime_http', 'responses_api', 'text_completion', 'vector_store_files', 'vector_stores', 'video'],
        ],
        'openai_like' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'openrouter' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['embedding', 'image_edit', 'image_generation', 'responses_api'],
        ],
        'ovhcloud' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['audio_transcription', 'embedding'],
        ],
        'parasail' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'perplexity' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['embedding', 'responses_api'],
        ],
        'petals' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => false, 'require_api_base' => true],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'pg_vector' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:vector_stores',
            'discovery' => 'manual',
            'modalities' => ['vector_stores'],
        ],
        'pinstripes' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'poe' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'predibase' => [
            'auth' => 'api_key_project',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'publicai' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'qwen_ai_platform' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['embedding', 'image_generation', 'rerank'],
        ],
        'qwencloud' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['embedding', 'image_generation', 'rerank'],
        ],
        'ragflow' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => ['vector_stores'],
        ],
        'recraft' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:image_edit,image_generation',
            'discovery' => 'manual',
            'modalities' => ['image_edit', 'image_generation'],
        ],
        'reducto' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:ocr',
            'discovery' => 'manual',
            'modalities' => ['ocr'],
        ],
        'replicate' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'runwayml' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:image_generation,text_to_speech,video',
            'discovery' => 'manual',
            'modalities' => ['image_generation', 'text_to_speech', 'video'],
        ],
        's3_vectors' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:vector_stores',
            'discovery' => 'manual',
            'modalities' => ['vector_stores'],
        ],
        'sagemaker' => [
            'auth' => 'aws_signature',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED_WITH_SPECIAL_AUTH',
            'modalities' => ['embedding'],
        ],
        'sagemaker_chat' => [
            'auth' => 'aws_signature',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED_WITH_SPECIAL_AUTH',
            'modalities' => [],
        ],
        'sagemaker_nova' => [
            'auth' => 'aws_signature',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED_WITH_SPECIAL_AUTH',
            'modalities' => [],
        ],
        'sambanova' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['embedding'],
        ],
        'sap' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => false, 'require_api_base' => true],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => ['embedding'],
        ],
        'scaleway' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => ['audio_transcription'],
        ],
        'scx-ai' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'snowflake' => [
            'auth' => 'api_key_account',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED',
            'modalities' => ['embedding'],
        ],
        'soniox' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:audio_transcription',
            'discovery' => 'manual',
            'modalities' => ['audio_transcription'],
        ],
        'stability' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:image_edit,image_generation',
            'discovery' => 'manual',
            'modalities' => ['image_edit', 'image_generation'],
        ],
        'synthetic' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'tencent' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['anthropic_messages'],
        ],
        'tensormesh' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'text-completion-codestral' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => false, 'require_api_base' => true],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'text-completion-inception' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['text_completion'],
        ],
        'text-completion-openai' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'together_ai' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['text_completion'],
        ],
        'topaz' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:image_variation,text_completion',
            'discovery' => 'manual',
            'modalities' => ['image_variation', 'text_completion'],
        ],
        'triton' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => false, 'require_api_base' => true],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => ['embedding'],
        ],
        'v0' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'valkey' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:vector_stores',
            'discovery' => 'manual',
            'modalities' => ['vector_stores'],
        ],
        'vercel_ai_gateway' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['embedding'],
        ],
        'vertex_ai' => [
            'auth' => 'gcp_service_account',
            'discovery' => 'live',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED_WITH_SPECIAL_AUTH',
            'modalities' => ['anthropic_messages', 'audio_transcription', 'files', 'google_genai_generate_content', 'image_edit', 'image_generation', 'ocr', 'rerank', 'text_completion', 'text_to_speech', 'vector_stores', 'video'],
        ],
        'vertex_ai_beta' => [
            'auth' => 'gcp_service_account',
            'discovery' => 'live',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED_WITH_SPECIAL_AUTH',
            'modalities' => [],
        ],
        'vllm' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => false, 'require_api_base' => true],
            'status' => 'SUPPORTED',
            'modalities' => ['passthrough', 'text_completion'],
        ],
        'volcengine' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['embedding', 'responses_api'],
        ],
        'voyage' => [
            'status' => 'NOT_CONFIGURABLE_FROM_HUB',
            'reason' => 'modality:embedding,rerank',
            'discovery' => 'manual',
            'modalities' => ['embedding', 'rerank'],
        ],
        'wandb' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'watsonx' => [
            'auth' => 'api_key_project',
            'discovery' => 'live',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED',
            'modalities' => ['audio_transcription', 'embedding', 'passthrough', 'rerank'],
        ],
        'watsonx_text' => [
            'auth' => 'api_key_project',
            'discovery' => 'live',
            'options' => ['require_api_key' => true],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],
        'xai' => [
            'auth' => 'api_key',
            'discovery' => 'live',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => ['responses_api', 'text_completion'],
        ],
        'xiaomi_mimo' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => [],
        ],
        'xinference' => [
            'auth' => 'api_key',
            'discovery' => 'manual',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED_WITH_MANUAL_MODEL',
            'modalities' => ['image_generation'],
        ],
        'zai' => [
            'auth' => 'api_key',
            'discovery' => 'catalog',
            'options' => ['require_api_key' => true, 'require_api_base' => false],
            'status' => 'SUPPORTED',
            'modalities' => [],
        ],

    ],

];
