<?php

/**
 * **كتالوجُ القدرات — الحقيقةُ البنيويّة** (سجلّ القدرات · §6/§7).
 *
 * مصدرُ الحقيقةِ الكوديُّ الواحد لِما تدعمه Lynomia. يقرؤه `App\Support\FeatureRegistry`
 * فيشتقُّ الحالةَ السارية من هنا + الإعدادات + الفاحصات. **بلا closures** (يُخبَّأ config:cache).
 *
 * قواعدُ الصدق: لا حالةَ متفائلة — الخارجيُّ/غيرُ المُهيَّأ يُشتقُّ من فاحصٍ (`derive`) لا
 * يُدّعى؛ والثوابتُ الأمنيّة `security_class => 'invariant'` (لا تُطفأ)؛ والمؤجَّلُ صريحٌ بسببه.
 * الحقولُ الناقصةُ تأخذ افتراضيّاتِ `FeatureRegistry::DEFAULTS`، فلا يُذكر إلا ما يختلف.
 */

return [

    /* ═══════════════════════ المجالات ═══════════════════════ */
    'domains' => [
        'collaboration' => ['label_ar' => 'التواصل والتعاون', 'label_en' => 'Collaboration', 'icon' => '💬', 'order' => 1, 'ia_domain' => 'communication'],
        'client'        => ['label_ar' => 'العملاء والتسليم', 'label_en' => 'Client / PSA', 'icon' => '🤝', 'order' => 2, 'ia_domain' => 'clients'],
        'work_os'       => ['label_ar' => 'نظام العمل', 'label_en' => 'Work OS', 'icon' => '🧩', 'order' => 3, 'ia_domain' => 'work'],
        'assets'        => ['label_ar' => 'الأصول والجرد', 'label_en' => 'Assets / Inventory', 'icon' => '📦', 'order' => 4, 'ia_domain' => 'work'],
        'telecom'       => ['label_ar' => 'الاتصالات', 'label_en' => 'Telecom', 'icon' => '📱', 'order' => 5, 'ia_domain' => 'work'],
        'security'      => ['label_ar' => 'الأمن', 'label_en' => 'Security', 'icon' => '🛡️', 'order' => 6, 'ia_domain' => 'administration'],
        'endpoint'      => ['label_ar' => 'النقاط الطرفيّة', 'label_en' => 'Endpoint', 'icon' => '💻', 'order' => 7, 'ia_domain' => 'administration'],
        'mobile'        => ['label_ar' => 'الجوال', 'label_en' => 'Mobile', 'icon' => '📲', 'order' => 8, 'ia_domain' => 'administration'],
        'platform'      => ['label_ar' => 'المنصّة والمطوّر', 'label_en' => 'Platform / Developer', 'icon' => '⚙️', 'order' => 9, 'ia_domain' => 'administration'],
    ],

    /* ═══════════════════════ القدرات ═══════════════════════ */
    'features' => [

        /* ───────── 7A · التعاون (v2.464–v2.469 · مُتحقَّق) ───────── */
        'collab.center' => ['domain' => 'collaboration', 'category' => 'center',
            'title_ar' => 'مركز التواصل الموحّد', 'title_en' => 'Unified Collaboration Center',
            'desc_ar' => 'ثلاثةُ ألواح فوق المحرّك الواحد — قنوات/غرف/مجموعات/محادثات.',
            'desc_en' => 'Three-pane center over the single engine.', 'status' => 'ENABLED',
            'account_types' => ['internal'], 'admin_surface' => 'collab.center', 'web_routes' => ['collab.center'],
            'api_routes' => ['mobile.conversations.index'], 'mobile_backend' => 'ready', 'native_mobile' => 'deferred',
            'openapi' => 'documented', 'introduced' => 'v2.467.0', 'docs' => 'docs/collaboration/07-unified-center.md'],
        'collab.channels' => ['domain' => 'collaboration', 'category' => 'messaging',
            'title_ar' => 'قنوات الفريق', 'title_en' => 'Team Channels', 'status' => 'ENABLED',
            'desc_ar' => 'قنواتٌ داخليّةٌ فوق حاوية المحادثة (comments).', 'desc_en' => 'Internal channels over the conversation container.',
            'web_routes' => ['conversations.index', 'conversations.show'], 'introduced' => 'v2.456.0', 'docs' => 'docs/collaboration/03-channel-management.md'],
        'collab.private_channels' => ['domain' => 'collaboration', 'category' => 'messaging',
            'title_ar' => 'قنوات خاصّة', 'title_en' => 'Private Channels', 'status' => 'ENABLED',
            'desc_ar' => 'قنواتٌ بالدعوة فقط — غيرُ قابلةٍ للاكتشاف.', 'desc_en' => 'Invite-only, non-discoverable.', 'introduced' => 'v2.456.0'],
        'collab.dm' => ['domain' => 'collaboration', 'category' => 'messaging',
            'title_ar' => 'الرسائل المباشرة', 'title_en' => 'Direct Messages', 'status' => 'ENABLED',
            'desc_ar' => 'خيوطٌ ثنائيّةٌ بمفتاحٍ من auth (خصوصيّة الطرفين).', 'desc_en' => 'Two-party threads, server-keyed.',
            'web_routes' => ['dm.inbox', 'dm.thread'], 'api_routes' => ['mobile.dm.threads'], 'mobile_backend' => 'ready', 'native_mobile' => 'deferred', 'openapi' => 'documented'],
        'collab.group_dm' => ['domain' => 'collaboration', 'category' => 'messaging',
            'title_ar' => 'مجموعات الرسائل', 'title_en' => 'Group DMs', 'status' => 'ENABLED',
            'desc_ar' => 'محادثاتٌ جماعيّةٌ خاصّةٌ — إضافةُ عضوٍ تُنشئ مجموعةً جديدة (أمنُ الجمهور التاريخيّ).',
            'desc_en' => 'Private group conversations; adding a member forks a new group.',
            'web_routes' => ['groups.index'], 'introduced' => 'v2.465.0', 'docs' => 'docs/collaboration/05-group-dms.md'],
        'collab.threads' => ['domain' => 'collaboration', 'category' => 'messaging', 'title_ar' => 'الخيوط', 'title_en' => 'Threads', 'status' => 'ENABLED', 'introduced' => 'v2.456.0'],
        'collab.reactions' => ['domain' => 'collaboration', 'category' => 'messaging', 'title_ar' => 'التفاعلات', 'title_en' => 'Reactions', 'status' => 'ENABLED',
            'api_routes' => ['mobile.comments.react', 'mobile.dm.react'], 'mobile_backend' => 'ready', 'introduced' => 'v2.456.0'],
        'collab.mentions' => ['domain' => 'collaboration', 'category' => 'messaging', 'title_ar' => 'الإشارات (Mentions)', 'title_en' => 'Mentions', 'status' => 'ENABLED',
            'desc_ar' => 'إشاراتٌ مُنطَّقةٌ بالمصرَّح لهم — لا تمنح وصولاً.', 'introduced' => 'v2.456.0'],
        'collab.saved' => ['domain' => 'collaboration', 'category' => 'messaging', 'title_ar' => 'المحفوظات', 'title_en' => 'Saved for Later', 'status' => 'ENABLED',
            'desc_ar' => 'محفوظاتٌ تُعادُ تخويلاً عند كلِّ فتح.', 'web_routes' => ['saved.index'], 'api_routes' => ['mobile.saved.index'], 'mobile_backend' => 'ready', 'introduced' => 'v2.456.0'],
        'collab.pins' => ['domain' => 'collaboration', 'category' => 'messaging', 'title_ar' => 'التثبيت (Pins)', 'title_en' => 'Pins', 'status' => 'ENABLED', 'introduced' => 'v2.456.0'],
        'collab.search' => ['domain' => 'collaboration', 'category' => 'messaging', 'title_ar' => 'بحث الرسائل', 'title_en' => 'Message Search', 'status' => 'ENABLED',
            'desc_ar' => 'بحثٌ منطَّقٌ بالعضويّة — لا يُرجِع قناةً لست فيها.', 'web_routes' => ['search.messages'], 'introduced' => 'v2.456.0'],
        'collab.unread' => ['domain' => 'collaboration', 'category' => 'messaging', 'title_ar' => 'حالة غير المقروء', 'title_en' => 'Unread State', 'status' => 'ENABLED', 'introduced' => 'v2.456.0'],
        'collab.directory' => ['domain' => 'collaboration', 'category' => 'management', 'title_ar' => 'دليل القنوات', 'title_en' => 'Channel Directory', 'status' => 'ENABLED',
            'web_routes' => ['conversations.directory'], 'introduced' => 'v2.456.0'],
        'collab.favorites' => ['domain' => 'collaboration', 'category' => 'management', 'title_ar' => 'المفضّلة', 'title_en' => 'Channel Favorites', 'status' => 'ENABLED', 'introduced' => 'v2.456.0'],
        'collab.archive' => ['domain' => 'collaboration', 'category' => 'management', 'title_ar' => 'أرشفة القنوات', 'title_en' => 'Channel Archive', 'status' => 'ENABLED', 'introduced' => 'v2.456.0'],
        'collab.notify_prefs' => ['domain' => 'collaboration', 'category' => 'management', 'title_ar' => 'تفضيلات الإشعار', 'title_en' => 'Notification Preferences', 'status' => 'ENABLED', 'introduced' => 'v2.456.0'],
        'collab.internal_rooms' => ['domain' => 'collaboration', 'category' => 'rooms', 'title_ar' => 'غرف المشاريع الداخليّة', 'title_en' => 'Project Internal Rooms', 'status' => 'ENABLED',
            'desc_ar' => 'غرفةٌ داخليّةٌ لكلِّ مشروع — معزولةٌ فيزيائيّاً عن العميل.', 'introduced' => 'v2.456.0', 'docs' => 'docs/collaboration/08-rooms-disclosure.md'],
        'collab.client_rooms' => ['domain' => 'collaboration', 'category' => 'rooms', 'title_ar' => 'غرف مشاريع العملاء', 'title_en' => 'Client Project Rooms', 'status' => 'ENABLED',
            'desc_ar' => 'غرفةُ عميلٍ بجمهورٍ صريح + تحذيرُ الناشر.', 'account_types' => ['internal', 'client'], 'introduced' => 'v2.468.0', 'docs' => 'docs/collaboration/08-rooms-disclosure.md'],
        'collab.record_discussions' => ['domain' => 'collaboration', 'category' => 'integration', 'title_ar' => 'مناقشات السجلات', 'title_en' => 'Record Discussions', 'status' => 'ENABLED',
            'desc_ar' => 'تعليقاتٌ على أيّ سجلٍّ عبر المفتاح متعدّد الأشكال.', 'introduced' => 'v2.456.0'],
        'collab.chat_commands' => ['domain' => 'collaboration', 'category' => 'integration', 'title_ar' => 'أوامر المحادثة', 'title_en' => 'Chat Commands', 'status' => 'ENABLED',
            'desc_ar' => '‏/task ‏/issue ‏/assign تُنشئ سجلاتٍ حقيقيّةً بحارس hub_can.', 'introduced' => 'v2.456.0', 'permissions' => ['tasks', 'issues']],
        'collab.presence' => ['domain' => 'collaboration', 'category' => 'realtime', 'title_ar' => 'الحضور', 'title_en' => 'Presence', 'status' => 'ENABLED',
            'desc_ar' => 'حضورٌ خشنٌ من نبضة الجلسة — للتواصل لا للمراقبة. قدرةٌ اختياريّةٌ قابلةٌ للإطفاء.',
            'toggleable' => true, 'setting_key' => 'feature.collab_presence', 'api_routes' => ['mobile.presence'], 'mobile_backend' => 'ready', 'introduced' => 'v2.466.0', 'docs' => 'docs/collaboration/06-presence-typing.md'],
        'collab.typing' => ['domain' => 'collaboration', 'category' => 'realtime', 'title_ar' => 'مؤشّر الكتابة', 'title_en' => 'Typing Indicators', 'status' => 'ENABLED',
            'desc_ar' => 'مؤشّرٌ عابرٌ في الذاكرة — لا يُخزَّن ولا يُدقَّق. قدرةٌ اختياريّةٌ قابلةٌ للإطفاء.',
            'toggleable' => true, 'setting_key' => 'feature.collab_typing', 'api_routes' => ['mobile.conversations.typing', 'mobile.dm.typing'], 'mobile_backend' => 'ready', 'introduced' => 'v2.466.0', 'docs' => 'docs/collaboration/06-presence-typing.md'],
        'collab.incremental_polling' => ['domain' => 'collaboration', 'category' => 'realtime', 'title_ar' => 'الاستطلاع التدريجيّ', 'title_en' => 'Incremental Polling', 'status' => 'ENABLED',
            'desc_ar' => 'جلبٌ تدريجيٌّ بمؤشّر keyset — النقلُ الحاليّ.', 'introduced' => 'v2.464.0', 'docs' => 'docs/collaboration/04-realtime.md'],
        'collab.event_contract' => ['domain' => 'collaboration', 'category' => 'realtime', 'title_ar' => 'عقد أحداث التعاون', 'title_en' => 'Collaboration Event Contract', 'status' => 'ENABLED',
            'desc_ar' => 'عقدُ أحداثٍ مستقرٌّ (message.created/deleted) — نفسُه للبثّ لاحقاً.', 'introduced' => 'v2.464.0'],
        'collab.websocket_readiness' => ['domain' => 'collaboration', 'category' => 'realtime', 'title_ar' => 'جاهزيّة WebSocket', 'title_en' => 'WebSocket Readiness', 'status' => 'READY',
            'desc_ar' => 'العقدُ جاهزٌ للبثّ (READY) — يستبدل الاستطلاعَ بلا تغيير الواجهة.', 'introduced' => 'v2.464.0'],
        'collab.websocket_provider' => ['domain' => 'collaboration', 'category' => 'realtime', 'title_ar' => 'مزوّد الزمن الحقيقيّ (WebSocket)', 'title_en' => 'WebSocket Provider', 'status' => 'NOT_CONFIGURED', 'derive' => 'websocket',
            'desc_ar' => 'لا مزوّدَ بثٍّ مُهيَّأً — لا Reverb/Redis/عمليّةَ دائمة.', 'depends' => ['collab.event_contract'], 'external_depends' => ['مزوّد WebSocket + عمليّة دائمة'], 'provider' => 'WebSocket provider'],
        'collab.voice_notes' => ['domain' => 'collaboration', 'category' => 'deferred', 'title_ar' => 'الملاحظات الصوتيّة', 'title_en' => 'Voice Notes', 'status' => 'DEFERRED',
            'desc_ar' => 'مؤجَّلةٌ كمنتَج — لا واجهةَ تسجيلٍ زائفة.', 'deferred_notes' => 'DEFERRED_PRODUCT_FEATURE — لا UI تسجيلٍ حتى يُقرَّر المنتَج'],
        'collab.link_previews' => ['domain' => 'collaboration', 'category' => 'deferred', 'title_ar' => 'معاينات الروابط', 'title_en' => 'Link Previews', 'status' => 'DEFERRED',
            'desc_ar' => 'مؤجَّلةٌ أمنيّاً — لا جلبَ خادميّ (تفادي SSRF).', 'deferred_notes' => 'DEFERRED_SECURITY_FEATURE — لا جلبَ خادميّ حتى تُصمَّم مضادّاتُ SSRF'],

        /* ───────── 7B · العملاء / PSA (Work OS · الطور B/D) ───────── */
        'client.portal' => ['domain' => 'client', 'category' => 'portal', 'title_ar' => 'بوّابة العميل', 'title_en' => 'Client Portal', 'status' => 'ENABLED',
            'account_types' => ['client'], 'desc_ar' => 'سطحُ العميل — فشلٌ مغلقٌ وأعمدةٌ عميليّةٌ حصراً (PortalGuard).', 'web_routes' => ['portal.home'], 'api_routes' => ['mobile.portal.home'], 'mobile_backend' => 'ready'],
        'client.activation' => ['domain' => 'client', 'category' => 'portal', 'title_ar' => 'تفعيل حساب العميل', 'title_en' => 'Client Account Activation', 'status' => 'ENABLED', 'account_types' => ['client']],
        'client.membership' => ['domain' => 'client', 'category' => 'portal', 'title_ar' => 'عضويّة العميل', 'title_en' => 'Client Membership', 'status' => 'ENABLED', 'permissions' => ['clients']],
        'client.project_access' => ['domain' => 'client', 'category' => 'delivery', 'title_ar' => 'وصول العميل للمشاريع', 'title_en' => 'Client Project Access', 'status' => 'ENABLED', 'account_types' => ['client']],
        'client.quote_provisioning' => ['domain' => 'client', 'category' => 'delivery', 'title_ar' => 'تحويل العرض إلى مشروع', 'title_en' => 'Quote → Project Provisioning', 'status' => 'ENABLED', 'permissions' => ['quotes', 'projects']],
        'client.internal_workspace' => ['domain' => 'client', 'category' => 'delivery', 'title_ar' => 'مساحة العمل الداخليّة للمشروع', 'title_en' => 'Internal Project Workspace', 'status' => 'ENABLED'],
        'client.workspace' => ['domain' => 'client', 'category' => 'delivery', 'title_ar' => 'مساحة العميل', 'title_en' => 'Client Workspace', 'status' => 'ENABLED', 'account_types' => ['client']],
        'client.external_delivery' => ['domain' => 'client', 'category' => 'delivery', 'title_ar' => 'تسليم المشاريع الخارجيّة', 'title_en' => 'External Project Delivery', 'status' => 'ENABLED'],
        'client.psa' => ['domain' => 'client', 'category' => 'delivery', 'title_ar' => 'إدارة مشاريع الخدمات (PSA)', 'title_en' => 'PSA Project Management', 'status' => 'ENABLED', 'permissions' => ['projects']],
        'client.visible_files' => ['domain' => 'client', 'category' => 'delivery', 'title_ar' => 'ملفّات مرئيّة للعميل', 'title_en' => 'Client-Visible Files', 'status' => 'ENABLED', 'account_types' => ['client'],
            'desc_ar' => 'مرشَّحةٌ بالجمهور (audience) — الداخليُّ لا يبلغ العميل.'],
        'client.visible_deliverables' => ['domain' => 'client', 'category' => 'delivery', 'title_ar' => 'مُخرَجات مرئيّة للعميل', 'title_en' => 'Client-Visible Deliverables', 'status' => 'ENABLED', 'account_types' => ['client']],
        'client.safe_timeline' => ['domain' => 'client', 'category' => 'delivery', 'title_ar' => 'خطٌّ زمنيٌّ آمنٌ للعميل', 'title_en' => 'Client-Safe Project Timeline', 'status' => 'ENABLED', 'account_types' => ['client']],

        /* ───────── 7C · نظام العمل (Work OS · الطور E/F/H) ───────── */
        'workos.financial_custody' => ['domain' => 'work_os', 'category' => 'finance', 'title_ar' => 'العهدة الماليّة', 'title_en' => 'Financial Custody', 'status' => 'ENABLED', 'permissions' => ['custody']],
        'workos.custody_ledger' => ['domain' => 'work_os', 'category' => 'finance', 'title_ar' => 'دفتر العهدة غير القابل للتعديل', 'title_en' => 'Custody Immutable Ledger', 'status' => 'ENABLED',
            'desc_ar' => 'قيودٌ لا تُعدَّل — التصحيحُ بقيدٍ عكسيّ.'],
        'workos.custody_receipt' => ['domain' => 'work_os', 'category' => 'finance', 'title_ar' => 'اشتراط إيصال العهدة', 'title_en' => 'Custody Receipt Requirement', 'status' => 'ENABLED'],
        'workos.custody_reversal' => ['domain' => 'work_os', 'category' => 'finance', 'title_ar' => 'ضبط عكس العهدة', 'title_en' => 'Custody Reversal Control', 'status' => 'ENABLED'],
        'workos.stations' => ['domain' => 'work_os', 'category' => 'stations', 'title_ar' => 'المحطّات', 'title_en' => 'Stations', 'status' => 'ENABLED', 'permissions' => ['stations']],
        'workos.station_identity' => ['domain' => 'work_os', 'category' => 'stations', 'title_ar' => 'هويّة المحطّة (QR/باركود)', 'title_en' => 'Station Identity / QR / Barcode', 'status' => 'ENABLED'],
        'workos.station_history' => ['domain' => 'work_os', 'category' => 'stations', 'title_ar' => 'سجلّ إسناد المحطّات', 'title_en' => 'Station Assignment History', 'status' => 'ENABLED'],
        'workos.employee_360' => ['domain' => 'work_os', 'category' => 'people', 'title_ar' => 'ملف الموظّف 360', 'title_en' => 'Employee 360', 'status' => 'ENABLED', 'permissions' => ['staff']],
        'workos.relationship_explorer' => ['domain' => 'work_os', 'category' => 'graph', 'title_ar' => 'مستكشف العلاقات', 'title_en' => 'Relationship Explorer', 'status' => 'ENABLED', 'web_routes' => ['graph.explore']],
        'workos.tech_workspace' => ['domain' => 'work_os', 'category' => 'graph', 'title_ar' => 'مساحة العمل التقنيّة', 'title_en' => 'Technical Workspace', 'status' => 'ENABLED'],
        'workos.project_360' => ['domain' => 'work_os', 'category' => 'delivery', 'title_ar' => 'مشروع 360', 'title_en' => 'Project 360', 'status' => 'ENABLED'],
        'workos.global_search' => ['domain' => 'work_os', 'category' => 'search', 'title_ar' => 'بحث نظام العمل الشامل', 'title_en' => 'Work OS Global Search', 'status' => 'ENABLED', 'web_routes' => ['search.index']],

        /* ───────── 7D · الأصول / الجرد (Work OS · الطور F) ───────── */
        'assets.company_assets' => ['domain' => 'assets', 'category' => 'inventory', 'title_ar' => 'أصول الشركة', 'title_en' => 'Company-Owned Assets', 'status' => 'ENABLED', 'permissions' => ['assets']],
        'assets.employee_assignment' => ['domain' => 'assets', 'category' => 'inventory', 'title_ar' => 'إسناد الأصول للموظّفين', 'title_en' => 'Employee Assignment', 'status' => 'ENABLED'],
        'assets.station_assignment' => ['domain' => 'assets', 'category' => 'inventory', 'title_ar' => 'إسناد الأصول للمحطّات', 'title_en' => 'Station Assignment', 'status' => 'ENABLED'],
        'assets.custody_history' => ['domain' => 'assets', 'category' => 'inventory', 'title_ar' => 'سجلّ عهدة الأصول', 'title_en' => 'Asset Custody History', 'status' => 'ENABLED'],
        'assets.inventory_sessions' => ['domain' => 'assets', 'category' => 'inventory', 'title_ar' => 'جلسات الجرد', 'title_en' => 'Inventory Sessions', 'status' => 'ENABLED'],
        'assets.scan_resolution' => ['domain' => 'assets', 'category' => 'inventory', 'title_ar' => 'مسح/حلّ الهويّة', 'title_en' => 'Scan / Identity Resolution', 'status' => 'ENABLED'],
        'assets.reconciliation' => ['domain' => 'assets', 'category' => 'inventory', 'title_ar' => 'مطابقة الجرد', 'title_en' => 'Reconciliation', 'status' => 'ENABLED'],
        'assets.endpoint_eligibility' => ['domain' => 'assets', 'category' => 'inventory', 'title_ar' => 'أهليّة النقطة الطرفيّة', 'title_en' => 'Endpoint Eligibility', 'status' => 'ENABLED'],
        'assets.relationship' => ['domain' => 'assets', 'category' => 'graph', 'title_ar' => 'استكشاف علاقات الأصول', 'title_en' => 'Asset Relationship Exploration', 'status' => 'ENABLED'],
        'assets.project_assignment' => ['domain' => 'assets', 'category' => 'inventory', 'title_ar' => 'إسناد الأصل للمشروع مباشرةً', 'title_en' => 'Direct Asset → Project Assignment', 'status' => 'DEFERRED',
            'desc_ar' => 'غيرُ أوّليّةٍ للأصول الماديّة: تُسنَد للموظّف/المحطّة لا للمشروع مباشرةً.',
            'deferred_notes' => 'غيرُ first-class للأصول الماديّة — الربطُ المباشر بالمشروع قائمٌ للأصول الرقميّة (DigitalAssets) وحدها. يُسجَّل بصدق لا يُختلَق ENABLED.'],

        /* ───────── 7E · الاتصالات (Work OS · الطور G) ───────── */
        'telecom.sim_registry' => ['domain' => 'telecom', 'category' => 'registry', 'title_ar' => 'سجلّ الشرائح (SIM)', 'title_en' => 'SIM Registry', 'status' => 'ENABLED', 'permissions' => ['sims']],
        'telecom.phone_registry' => ['domain' => 'telecom', 'category' => 'registry', 'title_ar' => 'سجلّ الأرقام', 'title_en' => 'Phone Number Registry', 'status' => 'ENABLED'],
        'telecom.carrier_registry' => ['domain' => 'telecom', 'category' => 'registry', 'title_ar' => 'سجلّ المشغّلين', 'title_en' => 'Carrier Registry', 'status' => 'ENABLED'],
        'telecom.sim_lifecycle' => ['domain' => 'telecom', 'category' => 'registry', 'title_ar' => 'دورة حياة الشريحة', 'title_en' => 'SIM Lifecycle', 'status' => 'ENABLED'],
        'telecom.employee_linkage' => ['domain' => 'telecom', 'category' => 'registry', 'title_ar' => 'ربط الموظّف', 'title_en' => 'Employee Linkage', 'status' => 'ENABLED'],
        'telecom.device_linkage' => ['domain' => 'telecom', 'category' => 'registry', 'title_ar' => 'ربط الجهاز', 'title_en' => 'Device Linkage', 'status' => 'ENABLED'],
        'telecom.station_linkage' => ['domain' => 'telecom', 'category' => 'registry', 'title_ar' => 'ربط المحطّة', 'title_en' => 'Station Linkage', 'status' => 'ENABLED'],
        'telecom.carrier_vault' => ['domain' => 'telecom', 'category' => 'security', 'title_ar' => 'خزنة اعتمادات المشغّل', 'title_en' => 'Carrier Credential Vaulting', 'status' => 'ENABLED',
            'desc_ar' => 'اعتماداتٌ مشفَّرةٌ — لا تخرج قيمتُها أبداً.'],
        'telecom.provisioning_adapter' => ['domain' => 'telecom', 'category' => 'integration', 'title_ar' => 'مُحوّل تزويد المشغّل', 'title_en' => 'Carrier Provisioning Adapter', 'status' => 'READY',
            'desc_ar' => 'الطبقةُ جاهزةٌ — تنتظر اعتماداتِ مشغّلٍ حيّة.'],
        'telecom.live_provisioning' => ['domain' => 'telecom', 'category' => 'integration', 'title_ar' => 'التزويد الحيّ من المشغّل', 'title_en' => 'Live Carrier Provisioning', 'status' => 'NOT_CONFIGURED',
            'desc_ar' => 'لا تكاملَ مشغّلٍ حيٍّ مُهيَّأ — لا يُدّعى ENABLED.', 'depends' => ['telecom.provisioning_adapter'], 'external_depends' => ['واجهة مشغّل الاتصالات (API + اعتمادات)'], 'provider' => 'Telecom carrier API'],

        /* ───────── 7F · الأمن ───────── */
        'security.app_ip_defense' => ['domain' => 'security', 'category' => 'network', 'title_ar' => 'دفاع IP على مستوى التطبيق', 'title_en' => 'Application IP Defense', 'status' => 'ENABLED', 'derive' => 'edge',
            'desc_ar' => 'الحجبُ الفعّالُ في طبقة التطبيق — نشطٌ دائماً.', 'admin_surface' => 'security.index'],
        'security.ip_allow' => ['domain' => 'security', 'category' => 'network', 'title_ar' => 'قواعد السماح (IP)', 'title_en' => 'IP Allow Rules', 'status' => 'ENABLED'],
        'security.ip_block' => ['domain' => 'security', 'category' => 'network', 'title_ar' => 'قواعد الحظر (IP)', 'title_en' => 'IP Block Rules', 'status' => 'ENABLED'],
        'security.auto_block' => ['domain' => 'security', 'category' => 'network', 'title_ar' => 'الحظر التلقائيّ للعناوين', 'title_en' => 'Automatic IP Blocking', 'status' => 'ENABLED'],
        'security.edge_blocking' => ['domain' => 'security', 'category' => 'network', 'title_ar' => 'الحجب عند الحافّة', 'title_en' => 'Edge-Level Blocking', 'status' => 'NOT_CONFIGURED', 'derive' => 'edge',
            'desc_ar' => 'يحتاج مزوّدَ حافّةٍ — التطبيقُ يحجب دونه.', 'external_depends' => ['مزوّد جدار حماية عند الحافّة'], 'provider' => 'Edge firewall provider'],
        'security.alerts' => ['domain' => 'security', 'category' => 'monitoring', 'title_ar' => 'تنبيهات الأمن', 'title_en' => 'Security Alerts', 'status' => 'ENABLED', 'admin_surface' => 'alerts.center'],
        'security.session_management' => ['domain' => 'security', 'category' => 'identity', 'title_ar' => 'إدارة الجلسات', 'title_en' => 'Session Management', 'status' => 'ENABLED', 'web_routes' => ['mysec.index']],
        'security.api_tokens' => ['domain' => 'security', 'category' => 'identity', 'title_ar' => 'إدارة رموز API', 'title_en' => 'API Token Management', 'status' => 'ENABLED'],
        'security.incident_investigation' => ['domain' => 'security', 'category' => 'monitoring', 'title_ar' => 'التحقيق في الحوادث', 'title_en' => 'Incident / Security Investigation', 'status' => 'ENABLED'],

        // الثوابتُ الأمنيّة — للرؤية فقط، لا تُطفأ أبداً (SYSTEM_INVARIANT)
        'security.authorization' => ['domain' => 'security', 'category' => 'invariant', 'title_ar' => 'التخويل الخادميّ (hub_can)', 'title_en' => 'Server-Authoritative Authorization', 'status' => 'SYSTEM_INVARIANT', 'security_class' => 'invariant'],
        'security.company_scopes' => ['domain' => 'security', 'category' => 'invariant', 'title_ar' => 'نطاقات الشركة', 'title_en' => 'Company Scopes', 'status' => 'SYSTEM_INVARIANT', 'security_class' => 'invariant'],
        'security.client_isolation' => ['domain' => 'security', 'category' => 'invariant', 'title_ar' => 'عزل العميل/الداخليّ', 'title_en' => 'Client/Internal Isolation', 'status' => 'SYSTEM_INVARIANT', 'security_class' => 'invariant'],
        'security.portal_guard' => ['domain' => 'security', 'category' => 'invariant', 'title_ar' => 'حارس البوّابة (PortalGuard)', 'title_en' => 'PortalGuard', 'status' => 'SYSTEM_INVARIANT', 'security_class' => 'invariant'],
        'security.audit_trail' => ['domain' => 'security', 'category' => 'invariant', 'title_ar' => 'سلسلة التدقيق', 'title_en' => 'Audit Trail', 'status' => 'SYSTEM_INVARIANT', 'security_class' => 'invariant',
            'desc_ar' => 'سلسلةُ SHA-256 لا تُمَسّ.'],
        'security.audit_chain_verification' => ['domain' => 'security', 'category' => 'invariant', 'title_ar' => 'تحقّق سلسلة التدقيق', 'title_en' => 'Audit Chain Verification', 'status' => 'SYSTEM_INVARIANT', 'security_class' => 'invariant'],
        'security.step_up' => ['domain' => 'security', 'category' => 'invariant', 'title_ar' => 'تأكيد الهويّة (Step-Up)', 'title_en' => 'Step-Up Security', 'status' => 'SYSTEM_INVARIANT', 'security_class' => 'invariant',
            'desc_ar' => 'حدودُ التأكيد الإلزاميّة — لا تصير مفتاحاً.'],
        'security.secret_encryption' => ['domain' => 'security', 'category' => 'invariant', 'title_ar' => 'تشفير الأسرار', 'title_en' => 'Secret Encryption', 'status' => 'SYSTEM_INVARIANT', 'security_class' => 'invariant'],
        'security.idor_defense' => ['domain' => 'security', 'category' => 'invariant', 'title_ar' => 'دفاعات IDOR', 'title_en' => 'IDOR Defenses', 'status' => 'SYSTEM_INVARIANT', 'security_class' => 'invariant'],

        /* ───────── 7G · النقاط الطرفيّة (EP) ───────── */
        'endpoint.enrollment' => ['domain' => 'endpoint', 'category' => 'lifecycle', 'title_ar' => 'تسجيل النقطة الطرفيّة', 'title_en' => 'Endpoint Enrollment', 'status' => 'ENABLED', 'permissions' => ['endpoints'], 'admin_surface' => 'endpoints.index'],
        'endpoint.identity' => ['domain' => 'endpoint', 'category' => 'lifecycle', 'title_ar' => 'هويّة النقطة الطرفيّة', 'title_en' => 'Endpoint Identity', 'status' => 'ENABLED'],
        'endpoint.agent' => ['domain' => 'endpoint', 'category' => 'agent', 'title_ar' => 'وكيل النقطة الطرفيّة', 'title_en' => 'Endpoint Agent', 'status' => 'ENABLED'],
        'endpoint.windows' => ['domain' => 'endpoint', 'category' => 'agent', 'title_ar' => 'دعم Windows', 'title_en' => 'Windows Support', 'status' => 'ENABLED'],
        'endpoint.macos' => ['domain' => 'endpoint', 'category' => 'agent', 'title_ar' => 'دعم macOS', 'title_en' => 'macOS Support', 'status' => 'ENABLED'],
        'endpoint.device_inventory' => ['domain' => 'endpoint', 'category' => 'lifecycle', 'title_ar' => 'جرد الأجهزة', 'title_en' => 'Device Inventory', 'status' => 'ENABLED'],
        'endpoint.wifi_posture' => ['domain' => 'endpoint', 'category' => 'posture', 'title_ar' => 'وضعيّة Wi-Fi', 'title_en' => 'Wi-Fi Posture', 'status' => 'ENABLED'],
        'endpoint.usb_observation' => ['domain' => 'endpoint', 'category' => 'posture', 'title_ar' => 'رصد USB', 'title_en' => 'USB Observation', 'status' => 'ENABLED',
            'desc_ar' => 'رصدٌ لا حجب — الحجبُ يحتاج MDM.'],
        'endpoint.usb_enforcement' => ['domain' => 'endpoint', 'category' => 'posture', 'title_ar' => 'إنفاذ USB', 'title_en' => 'USB Enforcement', 'status' => 'NOT_CONFIGURED', 'derive' => 'usb.enforce',
            'desc_ar' => 'لا يُعرَض ENABLED دون MDM حيٍّ يُنفِذ.', 'depends' => ['endpoint.usb_observation', 'endpoint.mdm'], 'external_depends' => ['مزوّد MDM'], 'provider' => 'MDM'],
        'endpoint.alerts' => ['domain' => 'endpoint', 'category' => 'monitoring', 'title_ar' => 'تنبيهات النقاط الطرفيّة', 'title_en' => 'Endpoint Security Alerts', 'status' => 'ENABLED'],
        'endpoint.commands' => ['domain' => 'endpoint', 'category' => 'control', 'title_ar' => 'أوامر النقطة الطرفيّة', 'title_en' => 'Endpoint Commands', 'status' => 'ENABLED'],
        'endpoint.isolation' => ['domain' => 'endpoint', 'category' => 'control', 'title_ar' => 'عزل النقطة الطرفيّة', 'title_en' => 'Endpoint Isolation', 'status' => 'ENABLED'],
        'endpoint.lock' => ['domain' => 'endpoint', 'category' => 'control', 'title_ar' => 'قفل النقطة الطرفيّة', 'title_en' => 'Endpoint Lock', 'status' => 'ENABLED'],
        'endpoint.release_distribution' => ['domain' => 'endpoint', 'category' => 'release', 'title_ar' => 'توزيع إصدارات الوكيل', 'title_en' => 'Endpoint Release Distribution', 'status' => 'ENABLED', 'web_routes' => ['endpoints.releases']],
        'endpoint.update' => ['domain' => 'endpoint', 'category' => 'release', 'title_ar' => 'تحديث النقطة الطرفيّة', 'title_en' => 'Endpoint Update', 'status' => 'ENABLED'],
        'endpoint.release_trust' => ['domain' => 'endpoint', 'category' => 'release', 'title_ar' => 'سلسلة ثقة الإصدار', 'title_en' => 'Release Trust', 'status' => 'ENABLED'],
        'endpoint.mdm' => ['domain' => 'endpoint', 'category' => 'integration', 'title_ar' => 'تكامل MDM', 'title_en' => 'MDM Integration', 'status' => 'NOT_CONFIGURED', 'derive' => 'usb.enforce',
            'desc_ar' => 'طبقةُ التكامل جاهزة — تنتظر مزوّدَ MDM.', 'external_depends' => ['مزوّد MDM'], 'provider' => 'MDM'],
        'endpoint.intune' => ['domain' => 'endpoint', 'category' => 'integration', 'title_ar' => 'Microsoft Intune', 'title_en' => 'Intune', 'status' => 'EXTERNAL',
            'desc_ar' => 'اعتمادٌ خارجيّ — لا اعتماداتٍ مُهيَّأة.', 'external_depends' => ['Microsoft Intune'], 'provider' => 'Microsoft Intune'],
        'endpoint.jamf' => ['domain' => 'endpoint', 'category' => 'integration', 'title_ar' => 'Jamf', 'title_en' => 'Jamf', 'status' => 'EXTERNAL',
            'external_depends' => ['Jamf'], 'provider' => 'Jamf'],
        'endpoint.production_signing' => ['domain' => 'endpoint', 'category' => 'signing', 'title_ar' => 'التوقيع الإنتاجيّ', 'title_en' => 'Production Signing', 'status' => 'NOT_CONFIGURED',
            'desc_ar' => 'لا يُعرَض ENABLED دون اعتماداتِ توقيعٍ حقيقيّة.', 'external_depends' => ['اعتمادات توقيعٍ إنتاجيّة'], 'provider' => 'Code signing authority'],
        'endpoint.windows_signing' => ['domain' => 'endpoint', 'category' => 'signing', 'title_ar' => 'توقيع Windows', 'title_en' => 'Windows Signing', 'status' => 'NOT_CONFIGURED', 'external_depends' => ['شهادة توقيع Windows (EV/OV)'], 'provider' => 'Windows code signing'],
        'endpoint.macos_signing' => ['domain' => 'endpoint', 'category' => 'signing', 'title_ar' => 'توقيع macOS', 'title_en' => 'macOS Signing', 'status' => 'NOT_CONFIGURED', 'external_depends' => ['Apple Developer ID'], 'provider' => 'Apple Developer ID'],
        'endpoint.apple_notarization' => ['domain' => 'endpoint', 'category' => 'signing', 'title_ar' => 'توثيق Apple (Notarization)', 'title_en' => 'Apple Notarization', 'status' => 'EXTERNAL',
            'depends' => ['endpoint.macos_signing'], 'external_depends' => ['خدمة توثيق Apple'], 'provider' => 'Apple notarization service'],
        'endpoint.signature_verification' => ['domain' => 'endpoint', 'category' => 'invariant', 'title_ar' => 'تحقّق توقيع النقطة الطرفيّة', 'title_en' => 'Endpoint Signature Verification', 'status' => 'SYSTEM_INVARIANT', 'security_class' => 'invariant',
            'desc_ar' => 'ES256 على كلِّ طلبِ نقطةٍ طرفيّة — مضادُّ إعادةٍ إلزاميّ.'],
        'endpoint.anti_replay' => ['domain' => 'endpoint', 'category' => 'invariant', 'title_ar' => 'مضادّ إعادة التشغيل', 'title_en' => 'Anti-Replay Protection', 'status' => 'SYSTEM_INVARIANT', 'security_class' => 'invariant'],

        /* ───────── 7H · الجوال ───────── */
        'mobile.backend' => ['domain' => 'mobile', 'category' => 'backend', 'title_ar' => 'خلفيّة الجوال', 'title_en' => 'Mobile Backend', 'status' => 'READY',
            'desc_ar' => 'الخلفيّةُ جاهزة؛ التطبيقُ الأصيلُ مؤجَّل.', 'admin_surface' => 'mobileplatform.index', 'mobile_backend' => 'ready', 'native_mobile' => 'deferred'],
        'mobile.auth_apis' => ['domain' => 'mobile', 'category' => 'api', 'title_ar' => 'واجهات مصادقة الجوال', 'title_en' => 'Mobile Authentication APIs', 'status' => 'ENABLED', 'mobile_backend' => 'ready', 'openapi' => 'documented', 'native_mobile' => 'deferred'],
        'mobile.collab_apis' => ['domain' => 'mobile', 'category' => 'api', 'title_ar' => 'واجهات تعاون الجوال', 'title_en' => 'Mobile Collaboration APIs', 'status' => 'ENABLED',
            'desc_ar' => 'الواجهاتُ حيّةٌ ومُختبَرة؛ الواجهةُ الأصيلةُ مؤجَّلة.', 'mobile_backend' => 'ready', 'openapi' => 'documented', 'native_mobile' => 'deferred', 'introduced' => 'v2.469.0'],
        'mobile.workos_apis' => ['domain' => 'mobile', 'category' => 'api', 'title_ar' => 'واجهات نظام العمل للجوال', 'title_en' => 'Mobile Work OS APIs', 'status' => 'ENABLED', 'mobile_backend' => 'ready', 'openapi' => 'documented', 'native_mobile' => 'deferred'],
        'mobile.openapi' => ['domain' => 'mobile', 'category' => 'api', 'title_ar' => 'مواصفة OpenAPI للجوال', 'title_en' => 'Mobile OpenAPI', 'status' => 'ENABLED', 'openapi' => 'documented', 'mobile_backend' => 'ready'],
        'mobile.native_app' => ['domain' => 'mobile', 'category' => 'deferred', 'title_ar' => 'التطبيق الأصيل', 'title_en' => 'Native Mobile App', 'status' => 'DEFERRED',
            'desc_ar' => 'قرارٌ استراتيجيّ: مؤجَّل. الخلفيّةُ جاهزةٌ متى بدأ.', 'depends' => ['mobile.backend'], 'native_mobile' => 'deferred',
            'deferred_notes' => 'قرارٌ استراتيجيٌّ ثابت — لا تطويرَ أصيل (Flutter/iOS/Android) في هذا النطاق. الخلفيّةُ والعقودُ محفوظة.'],
        'mobile.production_push' => ['domain' => 'mobile', 'category' => 'external', 'title_ar' => 'الدفع الإنتاجيّ', 'title_en' => 'Production Push', 'status' => 'NOT_CONFIGURED', 'derive' => 'push',
            'desc_ar' => 'السائقُ الصفريُّ لا يزيّف نجاحاً — يحتاج اعتماداتِ مزوّد.', 'external_depends' => ['مزوّد دفعٍ (FCM/APNs)'], 'provider' => 'Push provider'],
        'mobile.store_release' => ['domain' => 'mobile', 'category' => 'deferred', 'title_ar' => 'إصدار المتجر', 'title_en' => 'Store Release', 'status' => 'DEFERRED',
            'depends' => ['mobile.native_app'], 'deferred_notes' => 'مؤجَّلٌ تبعاً لتأجيل التطبيق الأصيل.'],

        /* ───────── 7I · المنصّة / المطوّر ───────── */
        'platform.api_surface' => ['domain' => 'platform', 'category' => 'api', 'title_ar' => 'سطح API (‏/api/v1)', 'title_en' => 'API Surface', 'status' => 'ENABLED', 'openapi' => 'documented', 'api_routes' => ['api.openapi']],
        'platform.openapi_generation' => ['domain' => 'platform', 'category' => 'api', 'title_ar' => 'توليد OpenAPI', 'title_en' => 'OpenAPI Generation', 'status' => 'ENABLED', 'openapi' => 'documented'],
        'platform.mobile_api_surface' => ['domain' => 'platform', 'category' => 'api', 'title_ar' => 'سطح API للجوال (‏/api/mobile/v1)', 'title_en' => 'Mobile API Surface', 'status' => 'ENABLED', 'openapi' => 'documented'],
        'platform.endpoint_api_surface' => ['domain' => 'platform', 'category' => 'api', 'title_ar' => 'سطح API للنقاط الطرفيّة', 'title_en' => 'Endpoint API Surface', 'status' => 'ENABLED'],
        'platform.system_trace' => ['domain' => 'platform', 'category' => 'observability', 'title_ar' => 'تتبّع النظام', 'title_en' => 'System Trace', 'status' => 'ENABLED', 'web_routes' => ['system.trace'], 'admin_surface' => 'system.trace'],
        'platform.integrations' => ['domain' => 'platform', 'category' => 'integration', 'title_ar' => 'سجلّ التكاملات', 'title_en' => 'Integrations Registry', 'status' => 'ENABLED', 'admin_surface' => 'integrations.index', 'web_routes' => ['integrations.index']],
        'platform.webhook_infra' => ['domain' => 'platform', 'category' => 'integration', 'title_ar' => 'بنية الويبهوك', 'title_en' => 'Webhook Infrastructure', 'status' => 'ENABLED', 'web_routes' => ['webhooks.index', 'hooks.index']],
        'platform.connection_checks' => ['domain' => 'platform', 'category' => 'integration', 'title_ar' => 'فاحصات الاتصال', 'title_en' => 'Connection Checks', 'status' => 'ENABLED',
            'desc_ar' => 'مسبارٌ واحدٌ يفحص المزوّدات — القيمُ مطموسة.'],
        'platform.audit_tools' => ['domain' => 'platform', 'category' => 'observability', 'title_ar' => 'أدوات التدقيق', 'title_en' => 'Audit Tools', 'status' => 'ENABLED', 'admin_surface' => 'audit.index', 'web_routes' => ['audit.index']],
        'platform.monitor_analytics' => ['domain' => 'platform', 'category' => 'observability', 'title_ar' => 'المراقبة والتحليلات', 'title_en' => 'Monitor / Analytics', 'status' => 'ENABLED', 'admin_surface' => 'control.index'],
        'platform.feature_registry' => ['domain' => 'platform', 'category' => 'governance', 'title_ar' => 'سجلّ القدرات', 'title_en' => 'Feature Registry', 'status' => 'ENABLED',
            'desc_ar' => 'هذا المركز — مصدرُ حقيقةِ القدرات الواحد.', 'admin_surface' => 'features.index', 'web_routes' => ['features.index', 'features.show'], 'introduced' => 'v2.470.0', 'docs' => 'docs/features/00-overview.md'],
    ],
];
