<?php

/** سجلُّ الوحدات — «accounts» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'accounts',
    'table' => 'platform_accounts',
    'model' => 'PlatformAccount',
    'label' => 'حسابات المنصات',
    'display' => 'platform',
    'status' => 'status',
    'columns' => [
        'platform',
        'projectId',
        'email',
        'status',
        'subExp',
    ],
    'fields' => [
        ['key' => 'vaultId', 'col' => 'vault_id', 'label' => 'سرّ الدخول (من الخزنة)', 'type' => 'ref', 'ref' => 'vault'],
        ['key' => 'twoFA', 'col' => 'two_fa', 'label' => 'التحقق الثنائي مفعّل', 'type' => 'bool'],
        [
            'key' => 'platform',
            'col' => 'platform',
            'label' => 'المنصة',
            'type' => 'sel',
            'options' => ['آبل', 'جوجل', 'مايكروسوفت', 'ميتا', 'تويتر/إكس', 'لينكدإن', 'أخرى'],
            'required' => true,
        ],
        [
            'key' => 'companyId',
            'col' => 'company_id',
            'label' => 'الشركة',
            'type' => 'ref',
            'ref' => 'companies',
        ],
        [
            'key' => 'projectId',
            'col' => 'project_id',
            'label' => 'المشروع',
            'type' => 'ref',
            'ref' => 'projects',
        ],
        [
            'key' => 'email',
            'col' => 'email',
            'label' => 'البريد المستخدم',
            'type' => 'text',
        ],
        [
            'key' => 'phone',
            'col' => 'phone',
            'label' => 'رقم الهاتف',
            'type' => 'text',
        ],
        [
            'key' => 'username',
            'col' => 'username',
            'label' => 'اسم المستخدم',
            'type' => 'text',
        ],
        [
            'key' => 'loginUrl',
            'col' => 'login_url',
            'label' => 'رابط تسجيل الدخول',
            'type' => 'url',
        ],
        [
            'key' => 'ownerId',
            'col' => 'owner_id',
            'label' => 'صاحب الحساب',
            'type' => 'ref',
            'ref' => 'users',
        ],
        [
            'key' => 'managerId',
            'col' => 'manager_id',
            'label' => 'مدير الحساب',
            'type' => 'ref',
            'ref' => 'users',
        ],
        [
            'key' => 'country',
            'col' => 'country',
            'label' => 'الدولة',
            'type' => 'sel',
            'options' => ['الكويت', 'السعودية', 'الإمارات', 'قطر', 'البحرين', 'عُمان', 'مصر', 'الأردن', 'أخرى'],
        ],
        [
            'key' => 'status',
            'col' => 'status',
            'label' => 'الحالة',
            'type' => 'sel',
            'options' => [
                'نشط',
                'قيد التحقق',
                'موقوف',
                'مغلق',
            ],
        ],
        [
            'key' => 'verified',
            'col' => 'verified',
            'label' => 'موثق؟',
            'type' => 'bool',
        ],
        [
            'key' => 'created',
            'col' => 'created',
            'label' => 'تاريخ الإنشاء',
            'type' => 'date',
        ],
        [
            'key' => 'subExp',
            'col' => 'sub_exp',
            'label' => 'انتهاء الاشتراك',
            'type' => 'date',
            'expiry' => true,
        ],
        [
            'key' => 'cost',
            'col' => 'cost',
            'label' => 'قيمة الاشتراك',
            'type' => 'num',
        ],
        [
            'key' => 'att',
            'col' => 'att_id',
            'label' => 'الملفات المرتبطة بالحساب',
            'type' => 'file',
        ],
        [
            'key' => 'pay',
            'col' => 'pay',
            'label' => 'وسيلة الدفع',
            'type' => 'text',
        ],
        [
            'key' => 'notes',
            'col' => 'notes',
            'label' => 'ملاحظات',
            'type' => 'ta',
        ],
    ],
    'search' => [
        'email',
        'phone',
        'username',
        'pay',
    ],
];
