<?php

/** سجلُّ الوحدات — «apis» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'apis',
    'table' => 'integrations_api',
    'model' => 'ApiIntegration',
    'label' => 'التكاملات و APIs',
    'display' => 'name',
    'status' => 'status',
    'columns' => [
        'name',
        'kind',
        'provider',
        'projectId',
        'env',
        'expiry',
        'status',
    ],
    'fields' => [
        [
            'key' => 'name',
            'col' => 'name',
            'label' => 'اسم التكامل / API',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'kind',
            'col' => 'kind',
            'label' => 'النوع',
            'type' => 'sel',
            'options' => [
                'API خارجي',
                'API داخلي',
                'Webhook',
                'بوابة دفع',
                'SMS',
                'شحن',
                'خرائط',
                'تحليلات',
                'أخرى',
            ],
        ],
        [
            'key' => 'projectId',
            'col' => 'project_id',
            'label' => 'المشروع',
            'type' => 'ref',
            'ref' => 'projects',
        ],
        [
            'key' => 'appId',
            'col' => 'app_id',
            'label' => 'التطبيق',
            'type' => 'ref',
            'ref' => 'apps',
        ],
        [
            'key' => 'provider',
            'col' => 'provider',
            'label' => 'المزوّد',
            'type' => 'text',
        ],
        [
            'key' => 'baseUrl',
            'col' => 'base_url',
            'label' => 'Base URL',
            'type' => 'url',
        ],
        [
            'key' => 'docs',
            'col' => 'docs',
            'label' => 'التوثيق',
            'type' => 'url',
        ],
        [
            'key' => 'authType',
            'col' => 'auth_type',
            'label' => 'نوع المصادقة',
            'type' => 'sel',
            'options' => [
                'API Key',
                'OAuth 2',
                'Bearer Token',
                'Basic',
                'بدون',
            ],
        ],
        [
            'key' => 'vaultId',
            'col' => 'vault_id',
            'label' => 'المفتاح (الخزنة)',
            'type' => 'ref',
            'ref' => 'vault',
        ],
        [
            'key' => 'env',
            'col' => 'env',
            'label' => 'البيئة',
            'type' => 'sel',
            'options' => [
                'إنتاج',
                'اختبار',
                'تطوير',
            ],
        ],
        [
            'key' => 'ownerId',
            'col' => 'owner_id',
            'label' => 'المسؤول',
            'type' => 'ref',
            'ref' => 'users',
        ],
        [
            'key' => 'quota',
            'col' => 'quota',
            'label' => 'الحد / الباقة',
            'type' => 'text',
        ],
        [
            'key' => 'cost',
            'col' => 'cost',
            'label' => 'التكلفة الشهرية',
            'type' => 'num',
        ],
        [
            'key' => 'expiry',
            'col' => 'expiry',
            'label' => 'انتهاء المفتاح',
            'type' => 'date',
            'expiry' => true,
        ],
        [
            'key' => 'status',
            'col' => 'status',
            'label' => 'الحالة',
            'type' => 'sel',
            'options' => [
                'نشط',
                'معطّل',
                'قيد الاختبار',
                'منتهي',
            ],
        ],
        [
            'key' => 'notes',
            'col' => 'notes',
            'label' => 'ملاحظات',
            'type' => 'ta',
        ],
    ],
    'search' => [
        'name',
        'provider',
        'quota',
    ],
];
