<?php

/** سجلُّ الوحدات — «approvals» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'approvals',
    'table' => 'approvals',
    'model' => 'Approval',
    'label' => 'الموافقات',
    'display' => 'title',
    'status' => 'status',
    'columns' => [
        'title',
        'type',
        'amount',
        'approverId',
        'due',
        'status',
    ],
    'fields' => [
        [
            'key' => 'title',
            'col' => 'title',
            'label' => 'عنوان الطلب',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'status',
            'col' => 'status',
            'label' => 'حالة الموافقة',
            'type' => 'sel',
            'required' => true,
            'options' => ['معلّق', 'معتمد', 'مرفوض', 'ملغى'],
            // حالة الحسم تُكتب من مسار الاعتماد/الرفض وحده (مع ختم
            // decided_by/decided_at) — لا من CRUD ولا كانبان ولا جملة
            'locked' => true,
        ],
        [
            'key' => 'type',
            'col' => 'type',
            'label' => 'نوع الطلب',
            'type' => 'sel',
            'required' => true,
            'options' => [
                'مصروف',
                'طلب شراء',
                'دفعة',
                'خصم / تخفيض',
                'إجازة',
                'عقد',
                'تغيير أسعار خدمة',
                'نشر تطبيق',
                'إطلاق تحديث',
                'اشتراك جديد',
                'إضافة مستخدم',
                'صلاحيات الخزنة',
                'حذف بيانات',
                'أخرى',
            ],
        ],
        [
            'key' => 'amount',
            'col' => 'amount',
            'label' => 'القيمة',
            'type' => 'num',
            'money' => true,
        ],
        [
            'key' => 'currency',
            'col' => 'currency',
            'label' => 'العملة',
            'type' => 'sel',
            'options' => ['د.ك', 'دولار', 'ريال', 'درهم', 'يورو', 'KWD'],
        ],
        [
            'key' => 'reason',
            'col' => 'reason',
            'label' => 'سبب الطلب',
            'type' => 'ta',
        ],
        [
            'key' => 'att',
            'col' => 'att_id',
            'label' => 'المرفقات',
            'type' => 'file',
        ],
        [
            'key' => 'chain',
            'col' => 'chain',
            'label' => 'مسار الموافقة (بالترتيب)',
            'type' => 'ref',
            'ref' => 'users',
            'multi' => true,
        ],
        [
            'key' => 'due',
            'col' => 'due',
            'label' => 'مطلوب قبل',
            'type' => 'date',
            'expiry' => true,
        ],
        [
            'key' => 'projectId',
            'col' => 'project_id',
            'label' => 'المشروع',
            'type' => 'ref',
            'ref' => 'projects',
        ],
        [
            'key' => 'appId',
            'col' => 'app_id',
            'label' => 'التطبيق (لطلبات النشر)',
            'type' => 'ref',
            'ref' => 'apps',
        ],
        [
            'key' => 'approverId',
            'col' => 'approver_id',
            'label' => 'الموافق المطلوب',
            'type' => 'ref',
            'required' => true,
            'ref' => 'users',
        ],
        [
            'key' => 'details',
            'col' => 'details',
            'label' => 'التفاصيل',
            'type' => 'ta',
        ],
    ],
    'search' => [
        'title',
        'reason',
        'details',
    ],
];
