<?php

/** سجلُّ الوحدات — «apps» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'apps',
    'table' => 'applications',
    'model' => 'Application',
    'label' => 'التطبيقات',
    'display' => 'name',
    'status' => 'status',
    'columns' => [
        'logo',
        'name',
        'projectId',
        'platform',
        'ver',
        'status',
        'downloads',
        'rating',
    ],
    'fields' => [
        [
            'key' => 'name',
            'col' => 'name',
            'label' => 'اسم التطبيق',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'logo',
            'col' => 'logo_id',
            'label' => 'الأيقونة / الشعار',
            'type' => 'img',
        ],
        [
            'key' => 'projectId',
            'col' => 'project_id',
            'label' => 'المشروع',
            'type' => 'ref',
            'ref' => 'projects',
        ],
        [
            'key' => 'platform',
            'col' => 'platform',
            'label' => 'المنصة',
            'type' => 'sel',
            'options' => [
                'Android',
                'iOS',
                'Android + iOS',
                'Web',
                'Desktop',
                'نظام داخلي',
            ],
        ],
        [
            'key' => 'status',
            'col' => 'status',
            'label' => 'الحالة',
            'type' => 'sel',
            'options' => [
                'قيد التطوير',
                'قيد المراجعة',
                'منشور',
                'بحاجة لتحديث',
                'موقوف',
            ],
        ],
        [
            'key' => 'ver',
            'col' => 'ver',
            'label' => 'الإصدار الحالي',
            'type' => 'text',
        ],
        [
            'key' => 'build',
            'col' => 'build',
            'label' => 'رقم Build',
            'type' => 'text',
        ],
        [
            'key' => 'autoStore',
            'col' => 'auto_store',
            'label' => 'مزامنة بيانات المتجر تلقائياً',
            'type' => 'bool',
        ],
        [
            'key' => 'downloads',
            'col' => 'downloads',
            'label' => 'التحميلات',
            'type' => 'num',
        ],
        [
            'key' => 'rating',
            'col' => 'rating',
            'label' => 'تقييم المتجر (٠–٥)',
            'type' => 'num',
        ],
        [
            'key' => 'reviews',
            'col' => 'reviews',
            'label' => 'عدد المراجعات',
            'type' => 'num',
        ],
        [
            'key' => 'pkg',
            'col' => 'pkg',
            'label' => 'Package Name',
            'type' => 'text',
        ],
        [
            'key' => 'bundle',
            'col' => 'bundle',
            'label' => 'Bundle ID',
            'type' => 'text',
        ],
        [
            'key' => 'lastUp',
            'col' => 'last_up',
            'label' => 'آخر تحديث',
            'type' => 'date',
        ],
        [
            'key' => 'nextUp',
            'col' => 'next_up',
            'label' => 'التحديث القادم',
            'type' => 'date',
            'expiry' => true,
        ],
        [
            'key' => 'devId',
            'col' => 'dev_id',
            'label' => 'المطور المسؤول',
            'type' => 'ref',
            'ref' => 'users',
        ],
        [
            'key' => 'fw',
            'col' => 'fw',
            'label' => 'Framework / اللغة',
            'type' => 'text',
        ],
        [
            'key' => 'api',
            'col' => 'api',
            'label' => 'رابط API',
            'type' => 'url',
        ],
        [
            'key' => 'git',
            'col' => 'git',
            'label' => 'Git Repository',
            'type' => 'url',
        ],
        [
            'key' => 'firebase',
            'col' => 'firebase',
            'label' => 'Firebase',
            'type' => 'url',
        ],
        [
            'key' => 'adminUrl',
            'col' => 'admin_url',
            'label' => 'لوحة إدارة التطبيق',
            'type' => 'url',
        ],
        [
            'key' => 'play',
            'col' => 'play',
            'label' => 'Google Play',
            'type' => 'url',
        ],
        [
            'key' => 'appstore',
            'col' => 'appstore',
            'label' => 'App Store',
            'type' => 'url',
        ],
        [
            'key' => 'huawei',
            'col' => 'huawei',
            'label' => 'AppGallery',
            'type' => 'url',
        ],
        [
            'key' => 'testUrl',
            'col' => 'test_url',
            'label' => 'رابط الاختبار',
            'type' => 'url',
        ],
        [
            'key' => 'published',
            'col' => 'published',
            'label' => 'منشور؟',
            'type' => 'bool',
        ],
        [
            'key' => 'appleRev',
            'col' => 'apple_rev',
            'label' => 'مراجعة Apple',
            'type' => 'sel',
            'options' => [
                '—',
                'قيد المراجعة',
                'مقبول',
                'مرفوض',
            ],
        ],
        [
            'key' => 'googleRev',
            'col' => 'google_rev',
            'label' => 'مراجعة Google',
            'type' => 'sel',
            'options' => [
                '—',
                'قيد المراجعة',
                'مقبول',
                'مرفوض',
            ],
        ],
        [
            'key' => 'supEmail',
            'col' => 'sup_email',
            'label' => 'بريد الدعم',
            'type' => 'text',
        ],
        [
            'key' => 'privacy',
            'col' => 'privacy',
            'label' => 'سياسة الخصوصية',
            'type' => 'url',
        ],
        [
            'key' => 'terms',
            'col' => 'terms',
            'label' => 'شروط الاستخدام',
            'type' => 'url',
        ],
        [
            'key' => 'delAcc',
            'col' => 'del_acc',
            'label' => 'رابط حذف الحساب',
            'type' => 'url',
        ],
        [
            'key' => 'supPhone',
            'col' => 'sup_phone',
            'label' => 'رقم الدعم',
            'type' => 'text',
        ],
        [
            'key' => 'gcloud',
            'col' => 'gcloud',
            'label' => 'Google Cloud',
            'type' => 'url',
        ],
        [
            'key' => 'appleDev',
            'col' => 'apple_dev',
            'label' => 'Apple Developer',
            'type' => 'url',
        ],
        [
            'key' => 'playCon',
            'col' => 'play_con',
            'label' => 'Google Play Console',
            'type' => 'url',
        ],
        [
            'key' => 'countries',
            'col' => 'countries',
            'label' => 'البلدان المتاح فيها',
            'type' => 'text',
        ],
        [
            'key' => 'subTypes',
            'col' => 'sub_types',
            'label' => 'أنواع الاشتراكات داخل التطبيق',
            'type' => 'text',
        ],
        [
            'key' => 'iap',
            'col' => 'iap',
            'label' => 'المنتجات داخل التطبيق',
            'type' => 'ta',
        ],
        [
            'key' => 'shots',
            'col' => 'shots_id',
            'label' => 'Screenshots / App Store Assets (ملف واحد)',
            'type' => 'file',
            // حقلُ الملف الواحد يبقى لما رُفع فيه سابقاً (أرشيفٌ مضغوط
            // مثلاً)، أمّا اللقطاتُ فصارت **معرضاً متعدداً** في مركز
            // التطبيق: تُرفع دفعةً وتُرتَّب وتُعرض صوراً لا أسماء ملفات.
            'hint' => 'اللقطات المتعددة تُرفع وتُرتَّب من «مركز التطبيق ← لقطات المتجر».',
        ],
        [
            'key' => 'keystore',
            'col' => 'keystore_id',
            'label' => 'Android Keystore (محمي)',
            'type' => 'file',
        ],
        [
            'key' => 'certs',
            'col' => 'certs_id',
            'label' => 'شهادات Apple / ملفات التوقيع (محمي)',
            'type' => 'file',
        ],
        [
            'key' => 'vaultId',
            'col' => 'vault_id',
            'label' => 'السر المرتبط بالتوقيع',
            'type' => 'ref',
            'ref' => 'vault',
        ],
        [
            'key' => 'desc',
            'col' => 'description',
            'label' => 'وصف التطبيق',
            'type' => 'ta',
        ],
        [
            'key' => 'notes',
            'col' => 'notes',
            'label' => 'ملاحظات',
            'type' => 'ta',
        ],
    ],
    'search' => [
        'name',
        'ver',
        'build',
        'pkg',
        'bundle',
    ],
];
