<?php

/** سجلُّ الوحدات — «budgets» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'budgets',
    'table' => 'budgets',
    'model' => 'Budget',
    'label' => 'الميزانيات',
    'display' => 'name',
    'status' => 'status',
    'columns' => [
        'name',
        'scope',
        'cat',
        'period',
        'amount',
        'status',
    ],
    'fields' => [
        [
            'key' => 'name',
            'col' => 'name',
            'label' => 'اسم الميزانية',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'scope',
            'col' => 'scope',
            'label' => 'النطاق',
            'type' => 'sel',
            'required' => true,
            'options' => [
                'شركة',
                'مشروع',
                'قسم',
                'مركز تكلفة',
            ],
        ],
        [
            'key' => 'companyId',
            'col' => 'company_id',
            'label' => 'الشركة',
            'type' => 'ref',
            'ref' => 'companies',
        ],
        [
            'key' => 'projectId',
            'col' => 'project_id',
            'label' => 'المشروع',
            'type' => 'ref',
            'ref' => 'projects',
        ],
        [
            'key' => 'ccId',
            'col' => 'cc_id',
            'label' => 'مركز التكلفة',
            'type' => 'ref',
            'ref' => 'costc',
        ],
        [
            'key' => 'dept',
            'col' => 'dept',
            'label' => 'القسم',
            'type' => 'text',
        ],
        [
            'key' => 'cat',
            'col' => 'cat',
            'label' => 'بند المصروف',
            'type' => 'sel',
            'options' => [
                'تطوير',
                'تصميم',
                'تسويق وإعلانات',
                'استضافة وسيرفرات',
                'اشتراكات وأدوات',
                'رواتب وأتعاب',
                'رسوم حكومية',
                'شحن وتوصيل',
                'أخرى',
                'الكل',
            ],
        ],
        [
            'key' => 'period',
            'col' => 'period',
            'label' => 'الفترة',
            'type' => 'sel',
            'options' => [
                'شهري',
                'ربع سنوي',
                'سنوي',
            ],
        ],
        [
            'key' => 'from',
            'col' => 'date_from',
            'label' => 'من',
            'type' => 'date',
        ],
        [
            'key' => 'to',
            'col' => 'date_to',
            'label' => 'إلى',
            'type' => 'date',
        ],
        [
            'key' => 'amount',
            'col' => 'amount',
            'label' => 'المبلغ المعتمد',
            'type' => 'num',
            'money' => true,
            'required' => true,
        ],
        [
            'key' => 'currency',
            'col' => 'currency',
            'label' => 'العملة',
            'type' => 'sel',
            'options' => ['د.ك', 'دولار', 'ريال', 'درهم', 'يورو'],
        ],
        [
            'key' => 'alertPct',
            'col' => 'alert_pct',
            'label' => 'تنبيه عند %',
            'type' => 'num',
        ],
        [
            'key' => 'status',
            'col' => 'status',
            'label' => 'الحالة',
            'type' => 'sel',
            'options' => [
                'نشطة',
                'مغلقة',
                'مسودة',
            ],
        ],
        [
            'key' => 'notes',
            'col' => 'notes',
            'label' => 'ملاحظات',
            'type' => 'ta',
        ],
    ],
    'search' => [
        'name',
        'dept',
    ],
];
