<?php

/** سجلُّ الوحدات — «clients» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'clients',
    'table' => 'clients',
    'model' => 'Client',
    'label' => 'العملاء (CRM)',
    'display' => 'name',
    'status' => 'stage',
    'columns' => [
        'name',
        'vip',
        'stage',
        'ownerId',
        'value',
        'lastTouch',
        'nextDate',
    ],
    'fields' => [
        ['key' => 'lostReason', 'col' => 'lost_reason', 'label' => 'سبب الخسارة', 'type' => 'sel',
         'options' => ['السعر', 'المزايا', 'التوقيت', 'منافس', 'لا ميزانية', 'بلا رد', 'أخرى']],
        ['key' => 'competitorId', 'col' => 'competitor_id', 'label' => 'خسرناه لصالح', 'type' => 'ref', 'ref' => 'competitors'],
        [
            'key' => 'name',
            'col' => 'name',
            'label' => 'اسم العميل / الشركة',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'vip',
            'col' => 'vip',
            'label' => 'عميل VIP',
            'type' => 'bool',
        ],
        [
            'key' => 'contact',
            'col' => 'contact',
            'label' => 'الشخص المسؤول',
            'type' => 'text',
        ],
        [
            'key' => 'email',
            'col' => 'email',
            'label' => 'البريد',
            'type' => 'text',
        ],
        [
            'key' => 'phone',
            'col' => 'phone',
            'label' => 'الهاتف',
            'type' => 'text',
        ],
        [
            'key' => 'country',
            'col' => 'country',
            'label' => 'الدولة',
            'type' => 'sel',
            'options' => ['الكويت', 'السعودية', 'الإمارات', 'قطر', 'البحرين', 'عُمان', 'مصر', 'الأردن', 'أخرى'],
        ],
        [
            'key' => 'companyId',
            'col' => 'company_id',
            'label' => 'شركتنا المرتبطة',
            'type' => 'ref',
            'ref' => 'companies',
        ],
        [
            'key' => 'ownerId',
            'col' => 'owner_id',
            'label' => 'مسؤول الحساب',
            'type' => 'ref',
            'ref' => 'users',
        ],
        [
            'key' => 'source',
            'col' => 'source',
            'label' => 'مصدر العميل',
            'type' => 'sel',
            'options' => [
                'إحالة',
                'سوشال ميديا',
                'الموقع',
                'معرض',
                'مكالمة باردة',
                'شريك',
                'أخرى',
            ],
        ],
        [
            'key' => 'stage',
            'col' => 'stage',
            'label' => 'المرحلة',
            'type' => 'sel',
            'options' => [
                'عميل محتمل',
                'تم التواصل',
                'عرض سعر',
                'تفاوض',
                'فوز',
                'خسارة',
                'عميل حالي',
            ],
        ],
        [
            'key' => 'value',
            'col' => 'value',
            'label' => 'قيمة الفرصة المتوقعة',
            'type' => 'num',
        ],
        [
            'key' => 'prob',
            'col' => 'prob',
            'label' => 'احتمال الإغلاق %',
            'type' => 'num',
        ],
        [
            'key' => 'services',
            'col' => 'services',
            'label' => 'الخدمات المهتم بها',
            'type' => 'ref',
            'ref' => 'services',
            'multi' => true,
        ],
        [
            'key' => 'lastTouch',
            'col' => 'last_touch',
            'label' => 'آخر تواصل',
            'type' => 'date',
        ],
        [
            'key' => 'nextStep',
            'col' => 'next_step',
            'label' => 'الخطوة التالية',
            'type' => 'text',
        ],
        [
            'key' => 'nextDate',
            'col' => 'next_date',
            'label' => 'موعد المتابعة',
            'type' => 'date',
            'expiry' => true,
        ],
        [
            'key' => 'notes',
            'col' => 'notes',
            'label' => 'ملاحظات',
            'type' => 'ta',
        ],
        [
            'key' => 'tags',
            'col' => 'tags',
            'label' => 'وسوم',
            'type' => 'tags',
        ],
    ],
    'search' => [
        'name',
        'contact',
        'email',
        'phone',
        'next_step',
    ],
];
