<?php

/** سجلُّ الوحدات — «companies» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'companies',
    'table' => 'companies',
    'model' => 'Company',
    'label' => 'الشركات',
    'display' => 'nameAr',
    'status' => 'status',
    'columns' => [
        'nameAr',
        'country',
        'type',
        'status',
        'phone',
    ],
    'fields' => [
        [
            'key' => 'nameAr',
            'col' => 'name_ar',
            'label' => 'اسم الشركة (عربي)',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'nameEn',
            'col' => 'name_en',
            'label' => 'الاسم (إنجليزي)',
            'type' => 'text',
        ],
        [
            'key' => 'logo',
            'col' => 'logo_id',
            'label' => 'الشعار',
            'type' => 'img',
        ],
        [
            'key' => 'country',
            'col' => 'country',
            'label' => 'الدولة',
            'type' => 'sel',
            'options' => ['الكويت', 'السعودية', 'الإمارات', 'قطر', 'البحرين', 'عُمان', 'مصر', 'الأردن', 'أخرى'],
        ],
        [
            'key' => 'city',
            'col' => 'city',
            'label' => 'المدينة',
            'type' => 'text',
        ],
        [
            'key' => 'type',
            'col' => 'type',
            'label' => 'نوع الشركة',
            'type' => 'sel',
            'options' => [
                'ذات مسؤولية محدودة',
                'مؤسسة فردية',
                'مساهمة',
                'فرع أجنبي',
                'أخرى',
            ],
        ],
        [
            'key' => 'status',
            'col' => 'status',
            'label' => 'الحالة',
            'type' => 'sel',
            'options' => [
                'نشطة',
                'قيد التأسيس',
                'متوقفة',
                'مغلقة',
            ],
        ],
        [
            'key' => 'regNo',
            'col' => 'reg_no',
            'label' => 'رقم السجل التجاري',
            'type' => 'text',
        ],
        [
            'key' => 'taxNo',
            'col' => 'tax_no',
            'label' => 'الرقم الضريبي',
            'type' => 'text',
        ],
        [
            'key' => 'founded',
            'col' => 'founded',
            'label' => 'تاريخ التأسيس',
            'type' => 'date',
        ],
        [
            'key' => 'activity',
            'col' => 'activity',
            'label' => 'النشاط التجاري',
            'type' => 'text',
        ],
        [
            'key' => 'email',
            'col' => 'email',
            'label' => 'البريد الرسمي',
            'type' => 'text',
        ],
        [
            'key' => 'phone',
            'col' => 'phone',
            'label' => 'رقم الهاتف',
            'type' => 'text',
        ],
        [
            'key' => 'website',
            'col' => 'website',
            'label' => 'الموقع الإلكتروني',
            'type' => 'url',
        ],
        [
            'key' => 'social',
            'col' => 'social',
            'label' => 'حسابات التواصل',
            'type' => 'text',
        ],
        [
            'key' => 'owner',
            'col' => 'owner',
            'label' => 'المالك',
            'type' => 'text',
        ],
        [
            'key' => 'currency',
            'col' => 'currency',
            'label' => 'العملة',
            'type' => 'sel',
            'options' => ['د.ك', 'دولار', 'ريال', 'درهم', 'يورو'],
        ],
        [
            'key' => 'partners',
            'col' => 'partners',
            'label' => 'الشركاء ونسب الملكية',
            'type' => 'ta',
        ],
        [
            'key' => 'address',
            'col' => 'address',
            'label' => 'العنوان',
            'type' => 'ta',
        ],
        [
            'key' => 'notes',
            'col' => 'notes',
            'label' => 'ملاحظات',
            'type' => 'ta',
        ],
        [
            'key' => 'tags',
            'col' => 'tags',
            'label' => 'وسوم',
            'type' => 'tags',
        ],
    ],
    'search' => [
        'name_ar',
        'name_en',
        'city',
        'reg_no',
        'tax_no',
    ],
];
