<?php

/** سجلُّ الوحدات — «contracts» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'contracts',
    'table' => 'contracts',
    'model' => 'Contract',
    'label' => 'العقود والالتزامات',
    'display' => 'title',
    'status' => 'status',
    'columns' => [
        'doc_no',
        'title',
        'type',
        'party',
        'value',
        'end',
        'status',
    ],
    'fields' => [
        ['key' => 'serviceId', 'col' => 'service_id', 'label' => 'الخدمة المباعة', 'type' => 'ref', 'ref' => 'services'],
        ['key' => 'planId', 'col' => 'plan_id', 'label' => 'الباقة', 'type' => 'ref', 'ref' => 'plans'],
        [
            'key' => 'title',
            'col' => 'title',
            'label' => 'اسم العقد',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'doc_no',
            'col' => 'doc_no',
            'label' => 'رقم العقد (يُولَّد تلقائياً إن تُرك فارغاً)',
            'type' => 'text',
        ],
        [
            'key' => 'type',
            'col' => 'type',
            'label' => 'النوع',
            'type' => 'sel',
            'required' => true,
            'options' => [
                'عقد عميل',
                'عقد مورد',
                'شراكة',
                'اتفاقية سرية NDA',
                'رخصة تجارية',
                'تسجيل حكومي',
                'علامة تجارية',
                'تأمين',
                'إيجار',
                'خارجي',
                'أخرى',
            ],
        ],
        [
            'key' => 'clientId',
            'col' => 'client_id',
            'label' => 'العميل',
            'type' => 'ref',
            'ref' => 'clients',
        ],
        [
            // عقودُ الارتباط الواحد تتجمع تحته: الأساسُ وملاحقُه وتجديداتُه
            'key' => 'engagementId',
            'col' => 'engagement_id',
            'label' => 'الارتباط',
            'type' => 'ref',
            'ref' => 'engagements',
        ],
        [
            'key' => 'companyId',
            'col' => 'company_id',
            'label' => 'الشركة',
            'type' => 'ref',
            'ref' => 'companies',
        ],
        [
            'key' => 'projectId',
            'col' => 'project_id',
            'label' => 'المشروع',
            'type' => 'ref',
            'ref' => 'projects',
        ],
        [
            'key' => 'party',
            'col' => 'party',
            'label' => 'الطرف الآخر',
            'type' => 'text',
        ],
        [
            'key' => 'value',
            'col' => 'value',
            'label' => 'القيمة',
            'type' => 'num',
            'money' => true,
        ],
        [
            'key' => 'currency',
            'col' => 'currency',
            'label' => 'العملة',
            'type' => 'sel',
            'options' => ['د.ك', 'دولار', 'ريال', 'درهم', 'يورو', 'KWD'],
        ],
        [
            'key' => 'start',
            'col' => 'date_start',
            'label' => 'تاريخ البداية',
            'type' => 'date',
        ],
        [
            'key' => 'end',
            'col' => 'date_end',
            'label' => 'تاريخ الانتهاء',
            'type' => 'date',
            'expiry' => true,
        ],
        [
            'key' => 'renewal',
            'col' => 'renewal',
            'label' => 'التجديد',
            'type' => 'sel',
            'options' => [
                'تلقائي',
                'يدوي',
                'لا يتجدد',
            ],
        ],
        [
            'key' => 'notice',
            'col' => 'notice',
            'label' => 'مدة الإشعار (يوم)',
            'type' => 'num',
        ],
        [
            'key' => 'ownerId',
            'col' => 'owner_id',
            'label' => 'المسؤول',
            'type' => 'ref',
            'ref' => 'users',
        ],
        [
            'key' => 'status',
            'col' => 'status',
            'label' => 'الحالة',
            'type' => 'sel',
            'options' => [
                'مسودة',
                'قيد التوقيع',
                'ساري',
                'منتهي',
                'ملغى',
                'قيد التجديد',
            ],
        ],
        [
            'key' => 'alerts',
            'col' => 'alerts',
            'label' => 'تنبيهات قبل (أيام)',
            'type' => 'text',
        ],
        [
            'key' => 'obligations',
            'col' => 'obligations',
            'label' => 'الالتزامات الرئيسية',
            'type' => 'ta',
        ],
        [
            'key' => 'att',
            'col' => 'att_id',
            'label' => 'نسخة العقد',
            'type' => 'file',
        ],
        [
            'key' => 'notes',
            'col' => 'notes',
            'label' => 'ملاحظات',
            'type' => 'ta',
        ],
    ],
    'search' => [
        'title',
        'doc_no',
        'party',
        'alerts',
        'obligations',
    ],
];
