<?php

/** سجلُّ الوحدات — «fin» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'fin',
    'table' => 'fin_documents',
    'model' => 'FinDocument',
    'label' => 'المحاسبة والفواتير',
    // حالاتٌ تُشتقّ من فعلٍ مجاليّ لا من سحب بطاقة (ARCH-03, v2.399): «مدفوعة» تعني مبلغاً مدفوعاً — يكتبها زرُّ الدفع
    'status_via_action' => [
        'مدفوعة' => 'حالةُ «مدفوعة» تُشتقّ من المبلغ المدفوع — سجّل الدفع من زر «دفع» لا بسحب البطاقة',
        'مدفوعة جزئياً' => 'حالةُ «مدفوعة جزئياً» تُشتقّ من المبلغ المدفوع — سجّل الدفعة من زر «دفع»',
    ],
    'display' => 'no',
    'status' => 'state',
    'columns' => [
        'no',
        'kind',
        'partner',
        'projectId',
        'date',
        'due',
        'total',
        'state',
    ],
    'fields' => [
        ['key' => 'serviceId', 'col' => 'service_id', 'label' => 'الخدمة', 'type' => 'ref', 'ref' => 'services'],
        [
            'key' => 'no',
            'col' => 'doc_no',
            'label' => 'رقم المستند',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'kind',
            'col' => 'kind',
            'label' => 'النوع',
            'type' => 'sel',
            'required' => true,
            'options' => [
                'فاتورة مبيعات',
                'فاتورة مشتريات',
                'مصروف',
                'دفعة واردة',
                'دفعة صادرة',
                'قيد يدوي',
            ],
        ],
        [
            'key' => 'projectId',
            'col' => 'project_id',
            'label' => 'المشروع',
            'type' => 'ref',
            'ref' => 'projects',
        ],
        [
            'key' => 'companyId',
            'col' => 'company_id',
            'label' => 'الشركة',
            'type' => 'ref',
            'ref' => 'companies',
        ],
        [
            'key' => 'partner',
            'col' => 'partner',
            'label' => 'العميل / المورد',
            'type' => 'text',
        ],
        [
            // ترقية الربط النصي إلى مرجع حقيقي — «partner» يبقى للمستندات
            // غير المرحَّلة وللموردين الذين ليسوا عملاء في السجل
            'key' => 'clientId',
            'col' => 'client_id',
            'label' => 'العميل (مرتبط)',
            'type' => 'ref',
            'ref' => 'clients',
        ],
        [
            'key' => 'date',
            'col' => 'date',
            'label' => 'التاريخ',
            'type' => 'date',
        ],
        [
            'key' => 'due',
            'col' => 'due',
            'label' => 'تاريخ الاستحقاق',
            'type' => 'date',
            'expiry' => true,
        ],
        [
            'key' => 'amount',
            'col' => 'amount',
            'label' => 'المبلغ قبل الضريبة',
            'type' => 'num',
            'money' => true,
        ],
        [
            'key' => 'tax',
            'col' => 'tax',
            'label' => 'الضريبة',
            'type' => 'num',
            'money' => true,
        ],
        [
            'key' => 'total',
            'col' => 'total',
            'label' => 'الإجمالي',
            'type' => 'num',
            'money' => true,
            'required' => true,
        ],
        [
            'key' => 'paid',
            'col' => 'paid',
            'label' => 'المدفوع',
            'type' => 'num',
            'money' => true,
            // مقفول سجلّياً: المدفوع يُحرَّك عبر إجراء «دفعة» (pay) وحده —
            // حيث يُسقَف بالمتبقي ويحرّك رصيد البنك ويولّد القيد. تحريرُه
            // يدويّاً كان يفكّه عن البنك والدفتر (فيضٌ/سالبٌ/فكّ ربط).
            'locked' => true,
        ],
        [
            'key' => 'currency',
            'col' => 'currency',
            'label' => 'العملة',
            'type' => 'sel',
            'options' => ['د.ك', 'دولار', 'ريال', 'درهم', 'يورو', 'KWD'],
        ],
        [
            'key' => 'state',
            'col' => 'state',
            'label' => 'الحالة',
            'type' => 'sel',
            'options' => [
                'مسودة',
                'معتمدة',
                'مرسلة',
                'مدفوعة جزئياً',
                'مدفوعة',
                'متأخرة',
                'ملغاة',
            ],
        ],
        [
            'key' => 'cat',
            'col' => 'cat',
            'label' => 'التصنيف',
            'type' => 'sel',
            'options' => [
                'تطوير',
                'تصميم',
                'تسويق وإعلانات',
                'استضافة وسيرفرات',
                'اشتراكات وأدوات',
                'رواتب وأتعاب',
                'رسوم حكومية',
                'شحن وتوصيل',
                'أخرى',
            ],
        ],
        [
            'key' => 'method',
            'col' => 'method',
            'label' => 'طريقة الدفع',
            'type' => 'sel',
            'options' => [
                'تحويل بنكي',
                'بطاقة',
                'نقدي',
                'KNET',
                'PayPal',
                'Stripe',
                'شيك',
                'أخرى',
            ],
        ],
        [
            'key' => 'bankId',
            'col' => 'bank_id',
            'label' => 'الحساب البنكي / الصندوق',
            'type' => 'ref',
            'ref' => 'banks',
        ],
        [
            'key' => 'ccId',
            'col' => 'cc_id',
            'label' => 'مركز التكلفة',
            'type' => 'ref',
            'ref' => 'costc',
        ],
        [
            'key' => 'ref',
            'col' => 'reference',
            'label' => 'مرجع خارجي',
            'type' => 'text',
        ],
        [
            'key' => 'odooId',
            'col' => 'odoo_id',
            'label' => 'معرّف أودو',
            'type' => 'text',
        ],
        [
            'key' => 'desc',
            'col' => 'description',
            'label' => 'البيان',
            'type' => 'ta',
        ],
        [
            'key' => 'att',
            'col' => 'att_id',
            'label' => 'المرفق',
            'type' => 'file',
        ],
        [
            'key' => 'tags',
            'col' => 'tags',
            'label' => 'وسوم',
            'type' => 'tags',
        ],
    ],
    'search' => [
        'doc_no',
        'partner',
        'reference',
        'odoo_id',
        'description',
    ],
];
