<?php

/** سجلُّ الوحدات — «hr» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'hr',
    'table' => 'employees',
    'model' => 'Employee',
    'label' => 'ملفات الموظفين',
    'display' => 'name',
    'status' => 'status',
    'columns' => [
        'name',
        'dept',
        'title',
        'managerId',
        'status',
        'iqamaExp',
    ],
    'fields' => [
        ['key' => 'email', 'col' => 'email', 'label' => 'البريد الإلكتروني', 'type' => 'text'],
        ['key' => 'phone', 'col' => 'phone', 'label' => 'رقم الهاتف', 'type' => 'text'],
        ['key' => 'nationality', 'col' => 'nationality', 'label' => 'الجنسية', 'type' => 'text'],
        ['key' => 'civilId', 'col' => 'civil_id', 'label' => 'الرقم المدني', 'type' => 'text'],
        ['key' => 'iban', 'col' => 'iban', 'label' => 'IBAN للتحويل', 'type' => 'text'],
        ['key' => 'emergency', 'col' => 'emergency', 'label' => 'جهة اتصال للطوارئ (اسم وهاتف)', 'type' => 'text'],
        [
            'key' => 'name',
            'col' => 'name',
            'label' => 'اسم الموظف',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'userId',
            'col' => 'user_id',
            'label' => 'حساب النظام',
            'type' => 'ref',
            'ref' => 'users',
        ],
        [
            'key' => 'companyId',
            'col' => 'company_id',
            'label' => 'الشركة',
            'type' => 'ref',
            'ref' => 'companies',
        ],
        [
            'key' => 'dept',
            'col' => 'dept',
            'label' => 'القسم',
            'type' => 'sel',
            'options' => [
                'إدارة',
                'تطوير',
                'تصميم',
                'تسويق',
                'مبيعات',
                'عمليات',
                'محاسبة',
                'دعم',
            ],
        ],
        [
            'key' => 'title',
            'col' => 'title',
            'label' => 'المسمى الوظيفي',
            'type' => 'text',
        ],
        [
            // ملفُ المندوب هو ملفُ الموظف نفسه — امتدادٌ لا نظامٌ موازٍ:
            // الحقلُ يميّز من يعمل ميدانياً فتُبنى عليه شاشاتُ الميدان
            'key' => 'fieldRole',
            'col' => 'field_role',
            'label' => 'الدور الميداني',
            'type' => 'sel',
            'options' => ['—', 'مندوب طبي', 'مشرف ميداني', 'مندوب مبيعات ميداني'],
        ],
        [
            'key' => 'managerId',
            'col' => 'manager_id',
            'label' => 'المدير المباشر',
            'type' => 'ref',
            'ref' => 'users',
        ],
        [
            'key' => 'hired',
            'col' => 'hired',
            'label' => 'تاريخ التعيين',
            'type' => 'date',
        ],
        [
            'key' => 'contract',
            'col' => 'contract',
            'label' => 'نوع العقد',
            'type' => 'sel',
            'options' => [
                'دوام كامل',
                'دوام جزئي',
                'مؤقت',
                'متعاقد',
                'تدريب',
            ],
        ],
        [
            'key' => 'salary',
            'col' => 'salary',
            'label' => 'الراتب الأساسي',
            'type' => 'num',
        ],
        [
            'key' => 'allow',
            'col' => 'allow',
            'label' => 'البدلات',
            'type' => 'num',
        ],
        [
            'key' => 'iqama',
            'col' => 'iqama',
            'label' => 'رقم الإقامة/الهوية',
            'type' => 'text',
        ],
        [
            'key' => 'iqamaExp',
            'col' => 'iqama_exp',
            'label' => 'انتهاء الإقامة',
            'type' => 'date',
            'expiry' => true,
        ],
        [
            'key' => 'passport',
            'col' => 'passport',
            'label' => 'رقم الجواز',
            'type' => 'text',
        ],
        [
            'key' => 'passExp',
            'col' => 'pass_exp',
            'label' => 'انتهاء الجواز',
            'type' => 'date',
            'expiry' => true,
        ],
        [
            'key' => 'leaveBal',
            'col' => 'leave_bal',
            'label' => 'رصيد الإجازات (يوم)',
            'type' => 'num',
        ],
        [
            'key' => 'status',
            'col' => 'status',
            'label' => 'الحالة',
            'type' => 'sel',
            'options' => [
                'نشط',
                'إجازة',
                'موقوف',
                'منتهية خدمته',
            ],
        ],
        [
            'key' => 'perf',
            'col' => 'perf',
            'label' => 'آخر تقييم أداء',
            'type' => 'sel',
            'options' => [
                'ممتاز',
                'جيد جداً',
                'جيد',
                'يحتاج تحسين',
            ],
        ],
        [
            'key' => 'assetIds',
            'col' => 'asset_ids',
            'label' => 'العهد المستلمة',
            'type' => 'ref',
            'ref' => 'assets',
            'multi' => true,
        ],
        [
            'key' => 'endDate',
            'col' => 'end_date',
            'label' => 'نهاية الخدمة',
            'type' => 'date',
        ],
        [
            'key' => 'notes',
            'col' => 'notes',
            'label' => 'ملاحظات',
            'type' => 'ta',
        ],
        [
            'key' => 'att',
            'col' => 'att_id',
            'label' => 'المستندات',
            'type' => 'file',
        ],
    ],
    'search' => [
        'name',
        'title',
        'iqama',
        'passport',
    ],
];
