<?php

/** سجلُّ الوحدات — «issues» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'issues',
    'table' => 'issues',
    'model' => 'Issue',
    'label' => 'المشاكل والمخاطر',
    'display' => 'title',
    'status' => 'status',
    'columns' => [
        'title',
        'kind',
        'projectId',
        'severity',
        'status',
    ],
    'fields' => [
        ['key' => 'likelihood', 'col' => 'likelihood', 'label' => 'احتمال الوقوع (للمخاطر)', 'type' => 'sel',
         'options' => ['شبه مؤكد', 'مرجّح', 'محتمل', 'نادر']],
        [
            'key' => 'title',
            'col' => 'title',
            'label' => 'العنوان',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'kind',
            'col' => 'kind',
            'label' => 'النوع',
            'type' => 'sel',
            'options' => [
                'مشكلة',
                'خطر',
            ],
        ],
        [
            'key' => 'projectId',
            'col' => 'project_id',
            'label' => 'المشروع',
            'type' => 'ref',
            'ref' => 'projects',
        ],
        [
            'key' => 'appId',
            'col' => 'app_id',
            'label' => 'التطبيق المتأثر',
            'type' => 'ref',
            'ref' => 'apps',
        ],
        [
            'key' => 'siteId',
            'col' => 'site_id',
            'label' => 'الموقع المتأثر',
            'type' => 'ref',
            'ref' => 'websites',
        ],
        [
            'key' => 'affected',
            'col' => 'affected',
            'label' => 'متأثر آخر (نص حر)',
            'type' => 'text',
        ],
        [
            'key' => 'ticketId',
            'col' => 'ticket_id',
            'label' => 'التذكرة المصدر',
            'type' => 'ref',
            'ref' => 'tickets',
        ],
        [
            'key' => 'severity',
            'col' => 'severity',
            'label' => 'درجة الخطورة',
            'type' => 'sel',
            'options' => ['حرجة', 'عالية', 'متوسطة', 'منخفضة'],
        ],
        [
            'key' => 'priority',
            'col' => 'priority',
            'label' => 'الأولوية',
            'type' => 'sel',
            'options' => ['عاجلة', 'عالية', 'متوسطة', 'منخفضة'],
        ],
        [
            'key' => 'riskCat',
            'col' => 'risk_cat',
            'label' => 'تصنيف الخطر (للنوع: خطر)',
            'type' => 'sel',
            'options' => [
                'تأخر الإطلاق',
                'مشكلة قانونية',
                'انتهاء ترخيص',
                'عدم توفر ميزانية',
                'مشكلة سيرفر',
                'مشكلة حساب مطور',
                'رفض التطبيق',
                'انتهاء دومين',
                'فقدان وصول لحساب',
                'الاعتماد على شخص واحد',
                'أخرى',
            ],
        ],
        [
            'key' => 'att',
            'col' => 'att_id',
            'label' => 'مرفق',
            'type' => 'file',
        ],
        [
            'key' => 'assigneeId',
            'col' => 'assignee_id',
            'label' => 'المسؤول',
            'type' => 'ref',
            'ref' => 'users',
        ],
        [
            'key' => 'found',
            'col' => 'found',
            'label' => 'تاريخ الاكتشاف',
            'type' => 'date',
        ],
        [
            // موعدُ المعالجة (v2.558): بلا موعدٍ لا يكون المعوّقُ مقبِضاً —
            // مالكٌ وحالةٌ بلا تاريخٍ يُسائَل عنده ليسا التزاماً
            'key' => 'due',
            'col' => 'due',
            'label' => 'موعد المعالجة',
            'type' => 'date',
        ],
        [
            'key' => 'status',
            'col' => 'status',
            'label' => 'الحالة',
            'type' => 'sel',
            'options' => [
                'مفتوحة',
                'قيد المعالجة',
                'محلولة',
                'مغلقة',
            ],
        ],
        [
            'key' => 'cause',
            'col' => 'cause',
            'label' => 'السبب',
            'type' => 'ta',
        ],
        [
            'key' => 'fix',
            'col' => 'fix',
            'label' => 'الحل المقترح',
            'type' => 'ta',
        ],
        [
            'key' => 'finalFix',
            'col' => 'final_fix',
            'label' => 'الحل النهائي',
            'type' => 'ta',
        ],
        [
            'key' => 'closed',
            'col' => 'closed',
            'label' => 'تاريخ الإغلاق',
            'type' => 'date',
        ],
    ],
    'search' => [
        'title',
        'affected',
        'cause',
        'fix',
        'final_fix',
    ],
];
