<?php

/** سجلُّ الوحدات — «projects» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'projects',
    'table' => 'projects',
    'model' => 'Project',
    'label' => 'المشاريع',
    'display' => 'name',
    'status' => 'status',
    'columns' => [
        'name',
        'companyId',
        'status',
        'priority',
        'progress',
        'managerId',
    ],
    'fields' => [
        [
            'key' => 'name',
            'col' => 'name',
            'label' => 'اسم المشروع',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'logo',
            'col' => 'logo_id',
            'label' => 'شعار المشروع',
            'type' => 'img',
        ],
        [
            'key' => 'companyId',
            'col' => 'company_id',
            'label' => 'الشركة المالكة',
            'type' => 'ref',
            'ref' => 'companies',
        ],
        [
            // المشروع يعرف عميلَه أخيراً: كان الوصلُ الوحيد عبر العروض
            // والعقود — فمشروعُ عميلٍ ومشروعُنا الداخلي سيّان في كل شاشة
            'key' => 'clientId',
            'col' => 'client_id',
            'label' => 'العميل (إن كان مشروعَ عميل)',
            'type' => 'ref',
            'ref' => 'clients',
            'hint' => 'اتركه فارغاً للمشروع الداخلي — وعبّئه فيدخل المشروعُ مساحةَ عمل عميله وربحيةَ ارتباطه.',
        ],
        [
            'key' => 'engagementId',
            'col' => 'engagement_id',
            'label' => 'الارتباط',
            'type' => 'ref',
            'ref' => 'engagements',
        ],
        [
            'key' => 'managerId',
            'col' => 'manager_id',
            'label' => 'مدير المشروع',
            'type' => 'ref',
            'ref' => 'users',
        ],
        [
            'key' => 'members',
            'col' => 'members',
            'label' => 'أعضاء الفريق',
            'type' => 'ref',
            'ref' => 'users',
            'multi' => true,
        ],
        [
            'key' => 'type',
            'col' => 'type',
            'label' => 'نوع المشروع',
            'type' => 'sel',
            'options' => [
                'تطبيق',
                'موقع',
                'متجر إلكتروني',
                'نظام داخلي',
                'خدمة',
                'أخرى',
            ],
        ],
        [
            'key' => 'status',
            'col' => 'status',
            'label' => 'حالة المشروع',
            'type' => 'sel',
            'options' => ['تخطيط', 'نشط', 'قيد التنفيذ', 'مراجعة', 'مكتمل', 'متوقف', 'ملغى'],
        ],
        [
            'key' => 'priority',
            'col' => 'priority',
            'label' => 'الأولوية',
            'type' => 'sel',
            'options' => ['عاجلة', 'عالية', 'متوسطة', 'منخفضة'],
        ],
        [
            'key' => 'progress',
            'col' => 'progress',
            'label' => 'نسبة الإنجاز %',
            'type' => 'num',
        ],
        [
            'key' => 'startDate',
            'col' => 'start_date',
            'label' => 'تاريخ البداية',
            'type' => 'date',
        ],
        [
            'key' => 'launchExp',
            'col' => 'launch_exp',
            'label' => 'الإطلاق المتوقع',
            'type' => 'date',
        ],
        [
            'key' => 'launchAct',
            'col' => 'launch_act',
            'label' => 'الإطلاق الفعلي',
            'type' => 'date',
        ],
        [
            'key' => 'market',
            'col' => 'market',
            'label' => 'السوق المستهدف',
            'type' => 'text',
        ],
        [
            'key' => 'countries',
            'col' => 'countries',
            'label' => 'الدول المستهدفة',
            'type' => 'text',
        ],
        [
            'key' => 'url',
            'col' => 'url',
            'label' => 'رابط المشروع',
            'type' => 'url',
        ],
        [
            'key' => 'staging',
            'col' => 'staging',
            'label' => 'بيئة الاختبار',
            'type' => 'url',
        ],
        [
            'key' => 'git',
            'col' => 'git',
            'label' => 'Git Repository',
            'type' => 'url',
        ],
        [
            'key' => 'desc',
            'col' => 'description',
            'label' => 'وصف المشروع',
            'type' => 'ta',
        ],
        [
            'key' => 'budget',
            'col' => 'budget',
            'label' => 'الميزانية',
            'type' => 'num',
            'money' => true,
        ],
        [
            'key' => 'cost',
            'col' => 'cost',
            'label' => 'التكلفة الفعلية',
            'type' => 'num',
            'money' => true,
        ],
        [
            'key' => 'revExp',
            'col' => 'rev_exp',
            'label' => 'الإيراد المتوقع',
            'type' => 'num',
            'money' => true,
        ],
        [
            'key' => 'currency',
            'col' => 'currency',
            'label' => 'العملة',
            'type' => 'sel',
            'options' => ['د.ك', 'دولار', 'ريال', 'درهم', 'يورو'],
        ],
        [
            'key' => 'prod',
            'col' => 'prod',
            'label' => 'بيئة الإنتاج',
            'type' => 'url',
        ],
        [
            'key' => 'brandColors',
            'col' => 'brand_colors',
            'label' => 'ألوان الهوية (افصل بفاصلة)',
            'type' => 'text',
        ],
        [
            'key' => 'brandFonts',
            'col' => 'brand_fonts',
            'label' => 'خطوط الهوية',
            'type' => 'text',
        ],
        [
            'key' => 'brandDesignerId',
            'col' => 'brand_designer_id',
            'label' => 'المصمم المسؤول',
            'type' => 'ref',
            'ref' => 'users',
        ],
        [
            'key' => 'notes',
            'col' => 'notes',
            'label' => 'ملاحظات الإدارة',
            'type' => 'ta',
        ],
        [
            'key' => 'tags',
            'col' => 'tags',
            'label' => 'وسوم',
            'type' => 'tags',
        ],
    ],
    'search' => [
        'name',
        'market',
        'countries',
        'description',
        'brand_colors',
    ],
];
