<?php

/** سجلُّ الوحدات — «recruit» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'recruit',
    'table' => 'candidates',
    'model' => 'Candidate',
    'label' => 'التوظيف',
    'display' => 'name',
    'status' => 'stage',
    'columns' => [
        'name',
        'job',
        'stage',
        'rating',
        'nextDate',
    ],
    'fields' => [
        ['key' => 'companyId', 'col' => 'company_id', 'label' => 'الشركة', 'type' => 'ref', 'ref' => 'companies'],
        [
            'key' => 'name',
            'col' => 'name',
            'label' => 'اسم المرشح',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'job',
            'col' => 'job',
            'label' => 'الوظيفة',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'dept',
            'col' => 'dept',
            'label' => 'القسم',
            'type' => 'sel',
            'options' => [
                'إدارة',
                'تطوير',
                'تصميم',
                'تسويق',
                'مبيعات',
                'عمليات',
                'محاسبة',
                'دعم',
            ],
        ],
        [
            'key' => 'email',
            'col' => 'email',
            'label' => 'البريد',
            'type' => 'text',
        ],
        [
            'key' => 'phone',
            'col' => 'phone',
            'label' => 'الهاتف',
            'type' => 'text',
        ],
        [
            'key' => 'source',
            'col' => 'source',
            'label' => 'المصدر',
            'type' => 'sel',
            'options' => [
                'لينكدإن',
                'إحالة موظف',
                'الموقع',
                'منصة توظيف',
                'أخرى',
            ],
        ],
        [
            'key' => 'stage',
            'col' => 'stage',
            'label' => 'المرحلة',
            'type' => 'sel',
            'options' => [
                'طلب جديد',
                'فرز أولي',
                'مقابلة أولى',
                'مقابلة فنية',
                'عرض وظيفي',
                'تم التعيين',
                'مرفوض',
            ],
        ],
        [
            'key' => 'expect',
            'col' => 'expect',
            'label' => 'الراتب المتوقع',
            'type' => 'num',
        ],
        [
            'key' => 'rating',
            'col' => 'rating',
            'label' => 'التقييم',
            'type' => 'sel',
            'options' => [
                'ممتاز',
                'جيد',
                'متوسط',
                'غير مناسب',
            ],
        ],
        [
            'key' => 'interviewer',
            'col' => 'interviewer',
            'label' => 'المُقابِل',
            'type' => 'ref',
            'ref' => 'users',
        ],
        [
            'key' => 'nextDate',
            'col' => 'next_date',
            'label' => 'الموعد القادم',
            'type' => 'dt',
        ],
        [
            'key' => 'cv',
            'col' => 'cv_id',
            'label' => 'السيرة الذاتية',
            'type' => 'file',
        ],
        [
            'key' => 'notes',
            'col' => 'notes',
            'label' => 'ملاحظات',
            'type' => 'ta',
        ],
    ],
    'search' => [
        'name',
        'job',
        'email',
        'phone',
    ],
];
