<?php

/** سجلُّ الوحدات — «subs» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'subs',
    'table' => 'subscriptions',
    'model' => 'Subscription',
    'label' => 'الاشتراكات والتجديدات',
    'display' => 'service',
    'status' => 'status',
    'columns' => [
        'service',
        'projectId',
        'cycle',
        'amount',
        'renew',
        'status',
    ],
    'fields' => [
        [
            'key' => 'service',
            'col' => 'service',
            'label' => 'اسم الخدمة',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'companyId',
            'col' => 'company_id',
            'label' => 'الشركة',
            'type' => 'ref',
            'ref' => 'companies',
        ],
        [
            'key' => 'projectId',
            'col' => 'project_id',
            'label' => 'المشروع',
            'type' => 'ref',
            'ref' => 'projects',
        ],
        [
            'key' => 'type',
            'col' => 'type',
            'label' => 'نوع الاشتراك',
            'type' => 'text',
        ],
        [
            'key' => 'cycle',
            'col' => 'cycle',
            'label' => 'دورة الدفع',
            'type' => 'sel',
            'options' => [
                'شهري',
                'ربع سنوي',
                'نصف سنوي',
                'سنوي',
                'مرة واحدة',
            ],
        ],
        [
            'key' => 'start',
            'col' => 'date_start',
            'label' => 'تاريخ البداية',
            'type' => 'date',
        ],
        [
            'key' => 'renew',
            'col' => 'renew',
            'label' => 'تاريخ التجديد',
            'type' => 'date',
            'required' => true,
            'expiry' => true,
        ],
        [
            'key' => 'amount',
            'col' => 'amount',
            'label' => 'القيمة',
            'type' => 'num',
            'money' => true,
        ],
        [
            'key' => 'currency',
            'col' => 'currency',
            'label' => 'العملة',
            'type' => 'sel',
            'options' => ['د.ك', 'دولار', 'ريال', 'درهم', 'يورو'],
        ],
        [
            'key' => 'pay',
            'col' => 'pay',
            'label' => 'وسيلة الدفع / البطاقة',
            'type' => 'text',
        ],
        [
            'key' => 'ownerId',
            'col' => 'owner_id',
            'label' => 'المسؤول',
            'type' => 'ref',
            'ref' => 'users',
        ],
        [
            'key' => 'autoRenew',
            'col' => 'auto_renew',
            'label' => 'تجديد تلقائي',
            'type' => 'bool',
        ],
        [
            'key' => 'status',
            'col' => 'status',
            'label' => 'الحالة',
            'type' => 'sel',
            'options' => [
                'نشط',
                'منتهي',
                'ملغي',
            ],
        ],
        [
            'key' => 'card',
            'col' => 'card',
            'label' => 'البطاقة المستخدمة',
            'type' => 'text',
        ],
        [
            'key' => 'cardExp',
            'col' => 'card_exp',
            'label' => 'انتهاء البطاقة',
            'type' => 'date',
            'expiry' => true,
        ],
        [
            'key' => 'invoiceUrl',
            'col' => 'invoice_url',
            'label' => 'رابط الفاتورة',
            'type' => 'url',
        ],
        [
            'key' => 'att',
            'col' => 'att_id',
            'label' => 'الفاتورة (مرفق)',
            'type' => 'file',
        ],
        [
            'key' => 'accUrl',
            'col' => 'acc_url',
            'label' => 'رابط الحساب',
            'type' => 'url',
        ],
        [
            'key' => 'alerts',
            'col' => 'alerts',
            'label' => 'تنبيهات قبل (أيام بفواصل — الافتراضي 90,60,30,15,7,1)',
            'type' => 'text',
        ],
        [
            'key' => 'notes',
            'col' => 'notes',
            'label' => 'ملاحظات',
            'type' => 'ta',
        ],
    ],
    'search' => [
        'service',
        'type',
        'pay',
        'card',
        'alerts',
    ],
];
