<?php

/** سجلُّ الوحدات — «tasks» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'tasks',
    'table' => 'tasks',
    'model' => 'Task',
    'label' => 'المهام',
    'display' => 'title',
    'status' => 'status',
    'columns' => [
        'title',
        'projectId',
        'assigneeId',
        'priority',
        'status',
        'due',
        'progress',
    ],
    'fields' => [
        [
            'key' => 'title',
            'col' => 'title',
            'label' => 'عنوان المهمة',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'projectId',
            'col' => 'project_id',
            'label' => 'المشروع',
            'type' => 'ref',
            'required' => true,
            'ref' => 'projects',
        ],
        [
            'key' => 'assigneeId',
            'col' => 'assignee_id',
            'label' => 'المسؤول',
            'type' => 'ref',
            'ref' => 'users',
        ],
        [
            'key' => 'parts',
            'col' => 'parts',
            'label' => 'المشاركون',
            'type' => 'ref',
            'ref' => 'users',
            'multi' => true,
        ],
        [
            'key' => 'featId',
            'col' => 'feat_id',
            'label' => 'المتطلب المنفَّذ (خيط التتبع)',
            'type' => 'ref',
            'ref' => 'feats',
        ],
        [
            'key' => 'priority',
            'col' => 'priority',
            'label' => 'الأولوية',
            'type' => 'sel',
            'options' => ['عاجلة', 'عالية', 'متوسطة', 'منخفضة'],
        ],
        [
            'key' => 'status',
            'col' => 'status',
            'label' => 'الحالة',
            'type' => 'sel',
            'options' => ['جديدة', 'قيد التنفيذ', 'مكتملة', 'متوقفة', 'ملغاة', 'منجزة'],
        ],
        [
            'key' => 'startDate',
            'col' => 'start_date',
            'label' => 'تاريخ البداية',
            'type' => 'date',
        ],
        [
            'key' => 'due',
            'col' => 'due',
            'label' => 'الموعد النهائي',
            'type' => 'date',
        ],
        [
            'key' => 'estH',
            'col' => 'est_h',
            'label' => 'الوقت المتوقع (س)',
            'type' => 'num',
        ],
        [
            'key' => 'actH',
            'col' => 'act_h',
            'label' => 'الوقت الفعلي (س)',
            'type' => 'num',
        ],
        [
            'key' => 'progress',
            'col' => 'progress',
            'label' => 'نسبة الإنجاز %',
            'type' => 'num',
        ],
        [
            'key' => 'dept',
            'col' => 'dept',
            'label' => 'القسم',
            'type' => 'sel',
            'options' => [
                'إدارة',
                'تطوير',
                'تصميم',
                'تسويق',
                'محتوى',
                'عمليات',
                'أخرى',
            ],
        ],
        [
            'key' => 'ticketId',
            'col' => 'ticket_id',
            'label' => 'التذكرة المصدر',
            'type' => 'ref',
            'ref' => 'tickets',
        ],
        [
            'key' => 'approval',
            'col' => 'approval',
            'label' => 'الاعتماد',
            'type' => 'sel',
            'options' => [
                'لا يلزم',
                'بانتظار اعتماد',
                'معتمدة',
                'مرفوضة',
            ],
        ],
        [
            'key' => 'lateReason',
            'col' => 'late_reason',
            'label' => 'سبب التأخير',
            'type' => 'ta',
        ],
        [
            'key' => 'att',
            'col' => 'att_id',
            'label' => 'مرفق',
            'type' => 'file',
        ],
        [
            'key' => 'desc',
            'col' => 'description',
            'label' => 'الوصف',
            'type' => 'ta',
        ],
        [
            'key' => 'tags',
            'col' => 'tags',
            'label' => 'وسوم',
            'type' => 'tags',
        ],
        ['key' => 'decisionId', 'col' => 'decision_id', 'label' => 'القرار المنبثقة عنه', 'type' => 'ref', 'ref' => 'decisions'],
    ],
    'search' => [
        'title',
        'late_reason',
        'description',
    ],
];
