<?php

/** سجلُّ الوحدات — «tickets» (docs/REORG_PLAN.md §R4) — يُحمَّل بترتيبه من قائمة config/hub.php */

return [
    'key' => 'tickets',
    'table' => 'tickets',
    'model' => 'Ticket',
    'label' => 'تذاكر العملاء',
    'display' => 'subject',
    'status' => 'status',
    'columns' => [
        'subject',
        'projectId',
        'customer',
        'cat',
        'priority',
        'status',
        
    ],
    'fields' => [
        ['key' => 'clientId', 'col' => 'client_id', 'label' => 'العميل', 'type' => 'ref', 'ref' => 'clients'],
        [
            'key' => 'subject',
            'col' => 'subject',
            'label' => 'موضوع التذكرة',
            'type' => 'text',
            'required' => true,
        ],
        [
            'key' => 'body',
            'col' => 'body',
            'label' => 'نص التذكرة / وصف المشكلة',
            'type' => 'ta',
        ],
        [
            'key' => 'projectId',
            'col' => 'project_id',
            'label' => 'المشروع',
            'type' => 'ref',
            'ref' => 'projects',
        ],
        [
            'key' => 'appId',
            'col' => 'app_id',
            'label' => 'التطبيق المرتبط',
            'type' => 'ref',
            'ref' => 'apps',
        ],
        [
            'key' => 'customer',
            'col' => 'customer',
            'label' => 'اسم العميل',
            'type' => 'text',
        ],
        [
            'key' => 'email',
            'col' => 'email',
            'label' => 'بريد العميل',
            'type' => 'text',
        ],
        [
            'key' => 'phone',
            'col' => 'phone',
            'label' => 'هاتف العميل',
            'type' => 'text',
        ],
        [
            'key' => 'channel',
            'col' => 'channel',
            'label' => 'القناة',
            'type' => 'sel',
            'options' => [
                'نموذج الموقع',
                'بريد إلكتروني',
                'واتساب',
                'هاتف',
                'داخل التطبيق',
                'API خارجي',
                'يدوي',
            ],
        ],
        [
            'key' => 'cat',
            'col' => 'cat',
            'label' => 'الفئة (تصنيف ذكي)',
            'type' => 'sel',
            'options' => [
                'عطل تقني',
                'حساب ودخول',
                'دفع وفواتير',
                'طلبات وشحن',
                'شكوى',
                'اقتراح',
                'استفسار عام',
            ],
        ],
        [
            'key' => 'priority',
            'col' => 'priority',
            'label' => 'الأولوية',
            'type' => 'sel',
            'options' => ['عاجلة', 'عالية', 'متوسطة', 'منخفضة', 'عاجلة جداً'],
        ],
        [
            'key' => 'status',
            'col' => 'status',
            'label' => 'الحالة',
            'type' => 'sel',
            'options' => [
                'جديدة',
                'قيد المعالجة',
                'بانتظار العميل',
                'محوّلة لمهمة',
                'تم الحل',
                'مغلقة',
            ],
        ],
        [
            'key' => 'assigneeId',
            'col' => 'assignee_id',
            'label' => 'المسؤول',
            'type' => 'ref',
            'ref' => 'users',
        ],
        [
            'key' => 'extId',
            'col' => 'ext_id',
            'label' => 'المعرّف الخارجي (API)',
            'type' => 'text',
        ],
        [
            'key' => 'tags',
            'col' => 'tags',
            'label' => 'وسوم',
            'type' => 'tags',
        ],
        [
            'key' => 'notes',
            'col' => 'notes',
            'label' => 'ملاحظات داخلية',
            'type' => 'ta',
        ],
    ],
    'search' => [
        'subject',
        'body',
        'customer',
        'email',
        'phone',
    ],
];
